final Map<String, String> ar = {
  "welcome": "مرحباً",
  "hello": "أهلاً",
  "categories": "الفئات",
  "gender_male": "ذكر",
  "gender_female": "أنثى",
  "disability_visual": "بصري",
  "disability_hearing": "سمعي",
  "disability_physical": "حركي",
  "disability_cognitive": "معرفي",
  "disability_other": "أخرى",
  "search_hint": "ابحث عن مؤسسات أو إرشادات...",
  "quick_access": "الوصول السريع",
  "emergency_call": "مكالمة طوارئ",
  "emergency_subtitle": "احصل على مساعدة فورية",
  "intelligent": "ذكي",
  "assistant": "مساعد",
  "medical": "طبي",
  "reminders": "تذكيرات",
  "accessibility": "إمكانية الوصول",
  "guidelines": "إرشادات",
  "learn_rights": "تعلم حقوقك ونصائح",
  "recommended": "مقترح لك",
  "no_recommendations": "لا توجد اقتراحات حالياً",
  "account": "الحساب",
  "personal_info": "المعلومات الشخصية",
  "my_bookings": "حجوزاتي",
  "support": "الدعم",
  "app_guidelines": "إرشادات التطبيق",
  "feedback": "ملاحظات",
  "appearance": "المظهر",
  "light_mode": "الوضع الفاتح",
  "dark_mode": "الوضع الداكن",
  "system_default": "افتراضي النظام",
  "Language":"اللغة",
  "app_slogan": "معك لاكتشاف قدراتك",
  "disability_profile": "الملف الإعاقة",
  "edit": "تعديل",
  "disability_description":
  "تساعدنا هذه المعلومات على تخصيص ميزات الوصول لك بشكل أفضل.",
  "visual_impairment": "إعاقة بصرية",
  "low_vision_mode": "وضع ضعف الإبصار مفعل",

  "profile": "الملف الشخصي",
  "log_out": "تسجيل الخروج",
  "personal_info_title": "المعلومات الشخصية",
  "required": "مطلوب",
  "invalid_age": "أدخل عمر صحيح",
  "profile_updated": "تم تحديث البيانات بنجاح",
  "select_gender" :"اختر النوع",
  "select_disability_type" :"اختر نوع الاعاقة",

  "app_guidelines_title": "إرشادات التطبيق",
  "how_can_we_help": "كيف يمكننا المساعدة؟",
  "search_help": "ابحث عن مساعدة...",
  "all_topics": "كل المواضيع",
  "accessibility_topic": "إمكانية الوصول",
  "chatbot_topic": "المساعد الذكي",
  "health_topic": "الصحة",
  "still_need_help": "هل تحتاج مساعدة؟",
  "contact_support": "تواصل مع الدعم",

  "full_name": "الاسم الكامل",
  "email": "البريد الإلكتروني",
  "phone": "رقم الهاتف",
  "age": "العمر",
  "gender": "النوع",
  "responsible_person": "الشخص المسؤول",
  "disability_type": "نوع الإعاقة",
  "save_changes": "حفظ التعديلات",
  "support_description":  "فريق الدعم متاح على مدار 24/7 لمساعدتك في أي مشكلات تتعلق بإمكانية الوصول.",
  'Name of guardian/responsible person' : "اسم الشخص المسؤول ",
  "my_bookings": "حجوزاتي",
  "no_bookings_found": "لا توجد حجوزات حتى الآن.",
  "booking_label_date": "التاريخ",
  "booking_label_time": "الوقت",
  "booking_label_amount": "المبلغ",
  "booking_label_method": "طريقة الدفع",
  "booking_status_prefix": "الحجز",
  "payment_status_prefix": "الدفع",
  "rate_institution": "تقييم المؤسسة",
  "rating_submitted_success": "تم إرسال تقييم المؤسسة بنجاح.",

  "status_confirmed": "مؤكد",
  "status_success": "ناجح",
  "status_failed": "فاشل",
  "status_pending_payment": "في انتظار الدفع",
  "status_pending": "معلق",

  "feedback_title": "التقييم",
  "feedback_select_rating_error": "يرجى اختيار تقييم أولاً.",
  "feedback_write_comment_error": "يرجى كتابة تعليقك.",
  "feedback_submitted_success": "تم إرسال التقييم بنجاح.",
  "feedback_question": "كيف كانت تجربتك؟",
  "feedback_description": "تقييمك يساعدنا على تحسين قدرة للجميع في المجتمع.",
  "feedback_rate_section": "قيّم تجربتك",
  "feedback_comments_section": "تعليقات إضافية",
  "feedback_comment_hint": "أخبرنا المزيد عن تجربتك...\nما الذي أعجبك؟ ما الذي يمكن تحسينه؟",
  "feedback_stood_out_section": "ما الذي لفت انتباهك؟",
  "feedback_tag_fast_response": "استجابة سريعة",
  "feedback_tag_ease_of_use": "سهولة الاستخدام",
  "feedback_tag_design": "التصميم",
  "feedback_tag_support": "الدعم",
  "feedback_submit": "إرسال التقييم",
  "feedback_terms": "بالإرسال، أنت توافق على شروط الخدمة.",

  "community_feed": "المجتمع",
  "all_posts": "كل المنشورات",
  "my_posts": "منشوراتي",
  "search_posts": "البحث في المنشورات",

  "create_post_title": "إنشاء منشور",
  "post_hint": "شارك شيئاً مع المجتمع...",
  "post_empty_error": "محتوى المنشور لا يمكن أن يكون فارغاً",
  "post_too_short_error": "محتوى المنشور قصير جداً",
  "publish_post": "نشر",
  "post_published_success": "تم نشر المنشور بنجاح",
  "failed_publish_post": "فشل نشر المنشور",

  "edit_post_title": "تعديل المنشور",
  "update_post_hint": "حدّث منشورك...",
  "post_updated_success": "تم تحديث المنشور بنجاح",
  "failed_update_post": "فشل تحديث المنشور",

  "delete_post_title": "حذف المنشور",
  "delete_post_confirm": "هل أنت متأكد من حذف هذا المنشور؟",
  "post_deleted_success": "تم حذف المنشور بنجاح",
  "failed_delete_post": "فشل حذف المنشور",

  "no_posts_found": "لا توجد منشورات",
  "retry": "إعادة المحاولة",
  "cancel": "إلغاء",
  "delete": "حذف",

  "comments_title": "التعليقات",
  "no_comments": "لا توجد تعليقات بعد",
  "write_comment_hint": "اكتب تعليقاً...",
  "comment_empty_error": "التعليق لا يمكن أن يكون فارغاً",
  "comment_too_short_error": "التعليق قصير جداً",
  "comment_updated_success": "تم تحديث التعليق بنجاح",
  "comment_deleted_success": "تم حذف التعليق بنجاح",
  "failed_add_comment": "فشل إضافة التعليق",
  "failed_update_comment": "فشل تحديث التعليق",
  "failed_delete_comment": "فشل حذف التعليق",

  "edit_comment_title": "تعديل التعليق",
  "update_comment_hint": "حدّث تعليقك...",

  "delete_comment_title": "حذف التعليق",
  "delete_comment_confirm": "هل أنت متأكد من حذف هذا التعليق؟",
  "payment_method_wallet": "المحفظة",
  "payment_method_card": "بطاقة بنكية",
  "payment_method_cash": "نقداً في المؤسسة",

  "institution_title": "مراكز الدعم",
  "institution_search_hint": "ابحث عن مؤسسة...",
  "institution_details_title": "تفاصيل المؤسسة",
  "institution_address": "العنوان",
  "institution_location": "الموقع",
  "institution_phone": "الهاتف",
  "institution_email": "البريد الإلكتروني",
  "institution_not_provided": "غير متوفر",
  "institution_open_in_maps": "فتح في الخرائط",
  "institution_services_title": "الخدمات",
  "institution_no_services": "لا توجد خدمات نشطة متاحة حالياً",
  "institution_view_details": "عرض التفاصيل",
  "institution_open_location_error": "تعذّر فتح رابط الموقع.",
  "institution_rate": "تقييم المؤسسة",

  "filter_all": "الكل",
  "filter_mobility": "حركي",
  "filter_vision": "بصري",
  "filter_hearing": "سمعي",
  "filter_cognitive": "معرفي",
  "filter_other": "أخرى",

  "empty_no_match_search_filter": "لا توجد مؤسسات تطابق بحثك والفلتر المحدد",
  "empty_no_match_search_filter_subtitle": "جرّب كلمة مختلفة أو اختر فئة أخرى أو امسح الفلاتر الحالية.",
  "empty_no_match_search": "لا توجد مؤسسات تطابق بحثك",
  "empty_no_match_search_subtitle": "جرّب كلمة مختلفة أو امسح البحث لرؤية جميع المؤسسات.",
  "empty_no_match_filter": "لا توجد مؤسسات في {filter}",
  "empty_no_match_filter_subtitle": "جرّب فئة أخرى أو امسح الفلتر لرؤية جميع المؤسسات.",
  "empty_no_institutions": "لا توجد مؤسسات",
  "empty_no_institutions_subtitle": "يرجى المحاولة مرة أخرى لاحقاً.",
  "clear_filters": "مسح الفلاتر",

  "results_showing_all_one": "عرض {count} مؤسسة",
  "results_showing_all_many": "عرض {count} مؤسسات",
  "results_showing_query_one": "عرض {count} نتيجة لـ \"{query}\"",
  "results_showing_query_many": "عرض {count} نتائج لـ \"{query}\"",
  "results_showing_filter_one": "عرض {count} مؤسسة في {filter}",
  "results_showing_filter_many": "عرض {count} مؤسسات في {filter}",
  "results_showing_both_one": "عرض {count} نتيجة لـ \"{query}\" في {filter}",
  "results_showing_both_many": "عرض {count} نتائج لـ \"{query}\" في {filter}",

  "service_free": "مجاني",
  "service_book_now": "احجز الآن",

  "recommended": "موصى به لك",
  "no_recommendations": "لا توجد توصيات.",
  "no_recommendations_available": "لا تتوفر توصيات في الوقت الحالي.",
  "categories": "الفئات",
  "physical": "حركي",
  "visual": "بصري",
  "hearing": "سمعي",


  "rate_institution": "تقييم المؤسسة",
  "select_your_rating": "اختر تقييمك",
  "your_rating": "تقييمك: {} / 5",
  "please_select_rating": "من فضلك اختر تقييم أولاً",
  "cancel": "إلغاء",
  "submit": "إرسال",
  "save_rating": "حفظ التقييم",

  "booking_card_payment_title": "الدفع بالبطاقة",
  "booking_card_info": "عند الضغط على الدفع، سيتم فتح صفحة الدفع التجريبية من Paymob لإتمام الدفع بالبطاقة بأمان.",
  "booking_pay_with_card": "الدفع بالبطاقة",
  "booking_checkout_error": "تعذّر فتح صفحة الدفع.",

  "booking_cash_title": "الدفع نقداً في المؤسسة",
  "booking_cash_info": "سيتم تأكيد حجزك فوراً، وسيتم تحصيل المبلغ في المؤسسة.",
  "booking_confirm": "تأكيد الحجز",

  "booking_checkout_title": "حجز الخدمة",
  "booking_select_datetime_error": "يرجى تحديد التاريخ والوقت أولاً.",
  "booking_continue_to_payment": "المتابعة للدفع",

  "booking_payment_method_title": "طريقة الدفع",
  "booking_choose_method": "اختر طريقة الدفع",
  "booking_method_card_title": "بطاقة بنكية",
  "booking_method_card_subtitle": "ادفع بأمان عبر صفحة Paymob التجريبية.",
  "booking_method_wallet_title": "محفظة إلكترونية",
  "booking_method_wallet_subtitle": "ادفع باستخدام محفظة جوال مدعومة عبر Paymob.",
  "booking_method_cash_title": "نقداً في المؤسسة",
  "booking_method_cash_subtitle": "أكّد الحجز الآن وادفع عند الحضور.",
  "booking_continue": "متابعة",

  "booking_wallet_title": "الدفع بالمحفظة",
  "booking_wallet_info": "عند الضغط على الدفع، سيتم فتح صفحة Paymob التجريبية لإتمام عملية الدفع بالمحفظة.",
  "booking_pay_with_wallet": "الدفع بالمحفظة",

  "booking_processing_title": "جارٍ المعالجة",
  "booking_processing_checking": "جارٍ التحقق من نتيجة الدفع...",
  "booking_processing_description": "يرجى الانتظار بينما نتحقق من حجزك مع Paymob ونحدّث الحالة النهائية.",

  "booking_result_title": "نتيجة الحجز",
  "booking_result_not_found_title": "الحجز غير موجود",
  "booking_result_not_found_message": "تعذّر تحميل هذا الحجز في الوقت الحالي.",
  "booking_result_confirmed_title": "تم تأكيد الحجز",
  "booking_result_confirmed_message": "تم تأكيد حجزك بنجاح.",
  "booking_result_processing_title": "لا تزال المعالجة جارية",
  "booking_result_processing_message": "عدت إلى التطبيق، لكن لم يكتمل التحديث النهائي بعد. يمكنك التحقق مجدداً من الصفحة الرئيسية.",
  "booking_result_cancelled_title": "تم إلغاء الحجز",
  "booking_result_cancelled_message": "تم إلغاء جلسة الدفع أو إبطالها.",
  "booking_result_failed_title": "فشل الحجز",
  "booking_result_failed_message": "لم تكتمل عملية الدفع بنجاح.",
  "booking_result_load_error": "تعذّر تحميل نتيجة الحجز في الوقت الحالي.",
  "booking_result_back_home": "العودة إلى الرئيسية",
  "booking_result_label_id": "رقم الحجز",
  "booking_result_label_booking_status": "حالة الحجز",
  "booking_result_label_payment_method": "طريقة الدفع",
  "booking_result_label_payment_status": "حالة الدفع",
  "booking_result_label_date": "التاريخ المطلوب",
  "booking_result_label_time": "الوقت المطلوب",
  "booking_result_unknown": "غير معروف",

  "booking_datetime_section_title": "تفاصيل الحجز",
  "booking_preferred_date": "التاريخ المفضّل",
  "booking_preferred_time": "الوقت المفضّل",
  "booking_select_date": "اختر تاريخاً",
  "booking_select_time": "اختر وقتاً",

  "booking_summary_category": "الفئة",
  "booking_summary_price": "السعر",
  "booking_summary_duration": "المدة",
  "booking_summary_date": "التاريخ",
  "booking_summary_time": "الوقت",
  "booking_summary_notes": "ملاحظات",
  "booking_summary_not_selected": "لم يتم الاختيار",
  "booking_summary_no_notes": "لا توجد ملاحظات إضافية",
  "booking_notes_title": "ملاحظات إضافية",
  "booking_notes_hint": "أضف أي ملاحظات أو تفاصيل للمؤسسة...",


      "emergency_help": "مساعدة طارئة",
"nearby_institutions": "مؤسسات قريبة",
"accessible_transport": "مواصلات مناسبة",
"my_rights": "حقوقي",

"type_message": "اكتب رسالة...",
"you": "أنت",
"ai_name": "قدرة AI",
"online": "متصل",
"clear_chat": "مسح المحادثة",
"app_name_ai": "قدرة AI",

  "medical_reminders": "التذكيرات الطبية",
  "today_progress": "تقدم اليوم",
  "doses_completed": "الجرعات المكتملة",
  "daily_reminders": "التذكيرات اليومية",
  "no_reminders": "لا توجد تذكيرات بعد. اضغط + لإضافة واحد",

  "taken": "تم",
  "swipe": "اسحب",
  "skip": "تخطي",

  "missed": "فات",
  "next_at": "التالي عند",
  "no_doses_scheduled": "لا توجد جرعات اليوم",
  "all_doses_completed": "تمت جميع الجرعات",
  "no_upcoming_doses": "لا توجد جرعات قادمة",

  "delete_reminder": "حذف التذكير؟",
  "delete": "حذف",
  "cancel": "إلغاء",

  "add_reminder": "إضافة تذكير",
  "medicine_name": "اسم الدواء",
  "dose_notes": "الجرعة / ملاحظات",
  "enter_medicine_name": "من فضلك أدخل اسم الدواء",
  "enter_dose_notes": "من فضلك أدخل الجرعة أو الملاحظات",
  "pick_time": "اختر الوقت",
  "choose_time": "من فضلك اختر وقت التذكير",
  "save": "حفظ",

  "accessibility_hub": "مركز إمكانية الوصول",
  "search_hint_a11y": "ابحث عن حقوق، نصائح، موارد...",
  "filter_all": "الكل",
  "filter_popular": "الأكثر شيوعاً",
  "category_visual": "البصري",
  "category_hearing": "السمعي",
  "category_physical": "الحركي",
  "category_cognitive": "الإدراكي",
  "category_other": "أخرى",
  "subtitle_visual": "العمى، ضعف البصر، عمى الألوان",
  "subtitle_hearing": "الصمم، ضعف السمع، لغة الإشارة",
  "subtitle_physical": "إعاقة حركية، كرسي متحرك",
  "subtitle_cognitive": "صعوبات التعلم، التنوع العصبي",
  "subtitle_other": "إعاقات الكلام، الإعاقات غير الظاهرة",
  "items_label": "عنصر",
  "no_resources": "لا توجد موارد بعد",
  "no_resources_category": "لا توجد موارد في هذه الفئة",
  "no_resources_found": "لا توجد موارد",
  "retry": "إعادة المحاولة",

  'sign_up': 'إنشاء حساب',
  'log_in': 'تسجيل الدخول',
  'sign_in': 'تسجيل الدخول',
  'login': 'دخول',

  'create_account': 'إنشاء حساب',
  'join_qudra': 'انضم إلى قدرة للوصول إلى خدمات مخصصة',
  'fill_all_fields': 'من فضلك أكمل جميع الحقول',
  'account_created': 'تم إنشاء الحساب بنجاح!',

  'full_name': 'الاسم الكامل',
  'full_name_hint': 'أدخل اسمك الكامل',
  'phone_number': 'رقم الهاتف',
  'phone_hint': 'مثال: 01234567890',
  'email_address': 'البريد الإلكتروني',
  'email_hint': 'name@example.com',
  'password': 'كلمة المرور',
  'password_hint': 'لا تقل عن 8 أحرف',
  'responsible_person': 'اسم المسؤول',
  'responsible_hint': 'اسم ولي الأمر',
  'age': 'العمر',
  'age_hint': 'مثال: 25',
  'gender': 'الجنس',
  'select': 'اختر',
  'disability_type_label': 'نوع الإعاقة',
  'select_type': 'اختر النوع',
  'gender_male': 'ذكر',
  'gender_female': 'أنثى',
  'already_have_account': 'لديك حساب بالفعل؟',
  'no_account': 'ليس لديك حساب؟',

  'tagline': '\"معك لاكتشاف قدرتك\"',
  'welcome_back': 'مرحباً بعودتك',
  'email_required': 'البريد الإلكتروني مطلوب',
  'email_invalid': 'أدخل بريداً إلكترونياً صحيحاً',
  'forgot_password_btn': 'نسيت كلمة المرور؟',

  'forgot_password_title': 'نسيت كلمة المرور',
  'reset_password_heading': 'إعادة تعيين\nكلمة المرور',
  'reset_password_desc': 'أدخل البريد الإلكتروني المرتبط بحسابك، وسنرسل لك رابطاً لإعادة تعيين كلمة المرور.',
  'email_note': 'تأكد أن هذا هو البريد الذي سجلت به.',
  'reset_password_btn': 'إعادة تعيين كلمة المرور',
  'remember_password': 'تتذكر كلمة المرور؟',

  'reset_password_title': 'إعادة تعيين كلمة المرور',
  'reset_password_instruction': 'أدخل رمز التحقق المرسل إلى بريدك الإلكتروني واختر كلمة مرور جديدة.',
  'verification_token': 'رمز التحقق',
  'token_hint': 'أدخل الرمز',
  'token_required': 'رمز التحقق مطلوب',
  'password_required': 'كلمة المرور مطلوبة',
  'min_6_chars': 'لا تقل عن 6 أحرف',
  'new_password': 'كلمة المرور الجديدة',
  'new_password_hint': 'أدخل كلمة المرور الجديدة',
  'confirm_password': 'تأكيد كلمة المرور الجديدة',
  'confirm_password_hint': 'أعد إدخال كلمة المرور',
  'confirm_password_required': 'من فضلك أكد كلمة المرور',
  'passwords_no_match': 'كلمتا المرور غير متطابقتين',
  'update_password': 'تحديث كلمة المرور',
  'password_updated': 'تم تحديث كلمة المرور بنجاح!',

      "unknown": "غير معروف",
"language_english": "الإنجليزية",
"language_arabic": "العربية",
"visual_assistance_mode": "وضع المساعدة البصرية",
"premium": "مميز",
"verified": "موثق",
"safety_topic": "السلامة",
"institutions_topic": "المؤسسات",
"app_guidelines_intro": "اعثر على إرشادات عملية حول المساعد الذكي، والتذكيرات الطبية، والمساعدة الطارئة، وأدوات إمكانية الوصول، ومراكز الدعم.",
"guidelines_support_description": "أرسل لنا ملاحظاتك أو بلّغ عن أي شيء غير واضح من خلال شاشة التقييم.",
"guideline_chatbot_title": "استخدام المساعد الذكي",
"guideline_chatbot_description": "افتح الوصول السريع واختر المساعد الذكي، أو انتقل إلى شاشة المحادثة من التطبيق. يمكنك طلب المساعدة في التنقل ودعم إمكانية الوصول.",
"open_chatbot": "فتح المساعد الذكي",
"guideline_reminders_title": "إعداد التذكيرات الطبية",
"guideline_reminders_description": "افتح الوصول السريع واختر التذكيرات الطبية. اضغط على زر الإضافة (+) لإضافة تذكير، واختر الوقت، ثم أدر كل جرعة بتحديد ما إذا تم أخذها أو تخطيها.",
"open_reminders": "فتح التذكيرات",
"guideline_accessibility_title": "تصفح موارد إمكانية الوصول",
"guideline_accessibility_description": "افتح الوصول السريع واختر إرشادات إمكانية الوصول لعرض الحقوق والنصائح والموارد المفيدة. يمكنك أيضًا استخدام شريط البحث وفلاتر الفئات داخل مركز إمكانية الوصول.",
"open_accessibility_hub": "فتح مركز إمكانية الوصول",
"guideline_emergency_title": "استخدام المساعدة الطارئة",
"guideline_emergency_description": "افتح الوصول السريع واختر مكالمة الطوارئ. من هناك يمكنك إدارة جهات اتصال الطوارئ، وفتح مسار الاستغاثة، والضغط المطول على زر SOS لتفعيل العد التنازلي للطوارئ.",
"open_emergency": "فتح الطوارئ",
"guideline_institutions_title": "العثور على مراكز الدعم",
"guideline_institutions_description": "استخدم شريط البحث في الصفحة الرئيسية أو افتح تبويب المؤسسات لتصفح مراكز الدعم النشطة. يمكنك تصفية المؤسسات حسب نوع الإعاقة وفتح التفاصيل قبل حجز الخدمة.",
"open_institutions": "فتح المؤسسات",
"guidelines_showing_all_one": "عرض {count} إرشاد",
"guidelines_showing_all_many": "عرض {count} إرشادات",
"guidelines_showing_query_one": "عرض {count} نتيجة لـ \"{query}\"",
"guidelines_showing_query_many": "عرض {count} نتائج لـ \"{query}\"",
"guidelines_showing_topic_one": "عرض {count} إرشاد في {topic}",
"guidelines_showing_topic_many": "عرض {count} إرشادات في {topic}",
"guidelines_showing_both_one": "عرض {count} نتيجة لـ \"{query}\" في {topic}",
"guidelines_showing_both_many": "عرض {count} نتائج لـ \"{query}\" في {topic}",
"no_guidelines_found": "لا توجد إرشادات",
"no_guidelines_found_desc": "جرّب كلمة أخرى أو امسح الفلتر المحدد لعرض جميع موضوعات الإرشاد.",

  "institution_portal_login_error": "هذا الحساب يخص بوابة المؤسسات. يُرجى استخدام تطبيق المؤسسات بدلًا من ذلك.",
  "login_invalid_credentials_error": "هذا البريد غير مسجل أو كلمة المرور غير صحيحة. يُرجى مراجعة بياناتك أو إنشاء حساب جديد أولًا.",
  "network_error_try_again": "تعذّر الاتصال الآن. يُرجى التحقق من الإنترنت والمحاولة مرة أخرى.",
  "too_many_login_attempts": "عدد محاولات تسجيل الدخول كبير جدًا. يُرجى الانتظار قليلًا ثم المحاولة مرة أخرى.",
  "login_failed_generic": "فشل تسجيل الدخول. يُرجى المحاولة مرة أخرى.",
  "signup_email_registered_error": "هذا البريد الإلكتروني مسجل بالفعل. يُرجى تسجيل الدخول بدلًا من ذلك.",
  "signup_institution_email_error": "هذا البريد الإلكتروني مسجل بالفعل كحساب مؤسسة. يُرجى استخدام تطبيق المؤسسات بدلًا من ذلك.",
  "signup_failed_generic": "فشل إنشاء الحساب. يُرجى المحاولة مرة أخرى.",

  "friend": "صديقي",
  "institution_about": "نبذة",
  "institution_no_description": "لا يوجد وصف متاح للمؤسسة حتى الآن.",
  "institution_availability_notes": "ملاحظات التوفر",
  "minutes_short": "د",
  "status_cancelled": "ملغي",
  "chat_welcome_message": "مرحبًا! أنا قدرة AI. كيف يمكنني مساعدتك اليوم؟",
  "resource_created_success": "تم إنشاء المورد بنجاح",
  "resource_updated_success": "تم تحديث المورد بنجاح",
  "resource_deleted_success": "تم حذف المورد بنجاح",

  "delete_reminder_confirm": "حذف \"{title}\"؟",
  "mark_as_taken": "تحديد كمأخوذ",
  "status_taken_today": "تم أخذه اليوم",
  "status_skipped_today": "تم تخطيه اليوم",
  "status_missed": "فات",
  "failed_load_reminders": "فشل تحميل التذكيرات",
  "valid_reminder_time": "يرجى اختيار وقت تذكير صالح",
  "failed_add_reminder": "فشل إضافة التذكير",
  "failed_delete_reminder": "فشل حذف التذكير",
  "failed_update_reminder_status": "فشل تحديث الحالة",
  "failed_mark_taken": "فشل تحديد الجرعة كمأخوذة",
  "failed_skip_dose": "فشل تخطي الجرعة",

  "emergency_title": "الطوارئ",
  "emergency_phase_placeholder": "تم اجتياز Phase 2 بنجاح.\nاربط هنا الشاشة الرئيسية في Phase 3.",
  "emergency_unexpected_error": "حدث خطأ غير متوقع.",
  "emergency_profile_setup_not_linked": "لم يتم ربط شاشة تعديل الملف الشخصي بعد.",
  "emergency_sos_not_linked": "سيتم ربط مسار SOS لاحقًا.",
  "emergency_contacts_not_linked": "سيتم ربط شاشة جهات الاتصال لاحقًا.",
  "emergency_load_error": "حدث خطأ أثناء تحميل بيانات الطوارئ.",
  "location_service_disabled_message": "خدمة الموقع مقفلة من الجهاز. فعّل الموقع أولًا للتمكن من مشاركة موقعك في الطوارئ.",
  "location_service_open_settings_message": "خدمة الموقع مقفلة من الجهاز. افتح إعدادات الموقع ثم حاول مرة أخرى.",
  "location_permission_denied_message": "لم يتم منح صلاحية الموقع بعد. يمكنك المحاولة مرة أخرى أو التخطي الآن.",
  "location_permission_error": "تعذر الوصول إلى صلاحية الموقع.",
  "emergency_direct_services": "خدمات الطوارئ المباشرة",
  "emergency_service_police": "الشرطة",
  "emergency_service_ambulance": "الإسعاف",
  "emergency_service_fire": "المطافي",
  "emergency_quick_needs": "احتياجات سريعة",
  "quick_need_cant_speak": "لا أستطيع التحدث",
  "quick_need_hard_of_hearing": "ضعف سمع",
  "quick_need_medical_case": "حالة طبية",
  "quick_need_need_caregiver": "أحتاج مقدم رعاية",
  "quick_need_in_danger": "أنا في خطر",
  "quick_need_need_help_now": "أحتاج مساعدة الآن",
  "emergency_location_ready": "الموقع جاهز للمشاركة",
  "emergency_location_not_ready": "الموقع غير جاهز حاليًا",
  "emergency_location_ready_subtitle": "سيتمكن التطبيق من مشاركة موقعك وقت الطوارئ.",
  "emergency_location_not_ready_subtitle": "تحقق من تشغيل خدمة الموقع أو تفعيل الصلاحية من إعدادات الهاتف.",
  "emergency_sos_press_hold": "اضغط مطولًا للتفعيل",
  "emergency_circle_title": "دائرة الطوارئ",
  "emergency_circle_add": "إضافة",
  "emergency_circle_manage": "إدارة",
  "emergency_circle_empty_title": "لا توجد جهات اتصال للطوارئ حتى الآن",
  "emergency_circle_empty_subtitle": "أضف أشخاصًا موثوقين مثل أحد الوالدين أو مقدم رعاية أو طبيب.",
  "emergency_circle_add_contacts": "إضافة جهات الاتصال",
  "emergency_contact_primary": "أساسي",
  "app_name": "قدرة",
  "emergency_contacts_title": "جهات اتصال الطوارئ",
  "emergency_contact_add": "إضافة جهة",
  "emergency_contact_add_single": "إضافة جهة اتصال",
  "emergency_contact_delete_title": "حذف جهة الاتصال",
  "emergency_contact_delete_confirm": "هل تريد حذف \"{name}\" من جهات اتصال الطوارئ؟",
  "emergency_contacts_empty_title": "لا توجد جهات اتصال للطوارئ",
  "emergency_contacts_empty_subtitle": "أضف أشخاصًا موثوقين مثل أحد الوالدين أو مقدم رعاية أو طبيب ليظهروا في الشاشة الرئيسية وفي بطاقة الطوارئ.",
  "emergency_contact_set_primary": "تعيين كأساسي",
  "emergency_active_title": "حالة طوارئ نشطة",
  "emergency_active_subtitle": "يمكنك الآن مشاركة حالتك أو موقعك أو التواصل مباشرة مع خدمات الطوارئ.",
  "emergency_current_location": "الموقع الحالي",
  "emergency_location_available_fallback": "الموقع متاح",
  "emergency_location_unavailable": "الموقع غير متاح حاليًا.",
  "emergency_send_urgent_alert": "ارسال استغاثه عاجله",
  "emergency_open_card": "فتح البطاقة",
  "emergency_card_not_linked": "سيتم ربط بطاقة الطوارئ في Phase 7.",
  "emergency_direct_call": "اتصال مباشر",
  "emergency_service_unified": "الطوارئ",
  "emergency_contacts_empty_inline": "لا توجد جهات اتصال للطوارئ حتى الآن.",
  "emergency_im_safe": "أنا بخير",
  "emergency_card_title": "بطاقة الطوارئ",
  "emergency_card_phase_placeholder": "تم اجتياز Phase 6 بنجاح.\nسيتم بناء بطاقة الطوارئ الكاملة في Phase 7.",
  "emergency_profile_setup_title": "إعداد الملف الشخصي للطوارئ",
  "emergency_profile_full_name_hint": "أدخل اسمك كما في الهوية",
  "emergency_blood_type": "فصيلة الدم",
  "emergency_select_blood_type": "اختر فصيلة الدم",
  "emergency_preferred_communication": "طريقة التواصل المفضلة",
  "emergency_communication_text": "كتابة",
  "emergency_communication_sign": "لغة إشارة",
  "emergency_communication_voice": "صوت",
  "emergency_important_medical_notes": "ملاحظات طبية هامة",
  "emergency_medical_notes_hint": "أي حالات طبية مزمنة أو معلومات ضرورية للمساعدة...",
  "emergency_allergies_medications": "الحساسية والأدوية",
  "emergency_allergies_hint": "قائمة بالحساسية من أطعمة أو أدوية، والأدوية الحالية...",
  "emergency_profile_local_save_notice": "يتم حفظ هذه البيانات محليًا على هذا الجهاز فقط لاستخدامها أثناء الطوارئ.",
  "emergency_vibration_alert_title": "تفعيل الاهتزاز عند التنبيه",
  "emergency_vibration_alert_subtitle": "استجابة لمسية قوية أثناء حالات الطوارئ",
  "emergency_saving": "جاري الحفظ...",
  "emergency_profile_section_title": "الملف الشخصي",
  "emergency_profile_no_data": "لا توجد بيانات ملف شخصي متاحة.",
  "emergency_medical_info_title": "المعلومات الطبية",
  "emergency_no_medical_notes": "لا توجد ملاحظات طبية مسجلة.",
  "emergency_no_allergies_medications": "لا توجد حساسية أو أدوية مسجلة.",
  "emergency_share_card": "مشاركة البطاقة",
  "emergency_sos_activation_title": "تفعيل الاستغاثة",
  "emergency_sos_activation_banner": "سيتم تفعيل حالة الطوارئ تلقائيًا بعد انتهاء العد التنازلي.",
  "emergency_sos_activation_countdown": "سيتم التفعيل خلال {seconds} ثوانٍ",
  "emergency_sos_activation_cancel_hint": "يمكنك الإلغاء الآن إذا تم الضغط بالخطأ.",
  "permission_location_title": "صلاحية الموقع غير\nمفعلة",
  "permission_location_subtitle": "نحتاج للوصول لموقعك الجغرافي للتمكن من مشاركته مع جهات اتصالك في حالة الطوارئ.",
  "permission_location_enabling": "جاري التفعيل...",
  "permission_location_enable": "تفعيل صلاحية الموقع",
  "permission_open_location_settings": "فتح إعدادات الموقع",
  "permission_skip_now": "تخطي الآن",
  "app_name": "قدرة",
  "emergency_contacts_title": "جهات اتصال الطوارئ",
  "emergency_contact_add": "إضافة جهة",
  "emergency_contact_add_single": "إضافة جهة اتصال",
  "emergency_contact_delete_title": "حذف جهة الاتصال",
  "emergency_contact_delete_confirm": "هل تريد حذف \"{name}\" من جهات اتصال الطوارئ؟",
  "emergency_contacts_empty_title": "لا توجد جهات اتصال للطوارئ",
  "emergency_contacts_empty_subtitle": "أضف أشخاصًا موثوقين مثل أحد الوالدين أو مقدم رعاية أو طبيب ليظهروا في الشاشة الرئيسية وفي بطاقة الطوارئ.",
  "emergency_contact_set_primary": "تعيين كأساسي",
  "emergency_contact_load_error": "تعذر تحميل جهات الاتصال.",
  "emergency_contact_add_error": "تعذر إضافة جهة الاتصال.",
  "emergency_contact_update_error": "تعذر تعديل جهة الاتصال.",
  "emergency_contact_delete_error": "تعذر حذف جهة الاتصال.",
  "emergency_contact_primary_error": "تعذر تحديث جهة الاتصال الأساسية.",
  "emergency_active_title": "حالة طوارئ نشطة",
  "emergency_active_subtitle": "يمكنك الآن مشاركة حالتك أو موقعك أو التواصل مباشرة مع خدمات الطوارئ.",
  "emergency_current_location": "الموقع الحالي",
  "emergency_location_available_fallback": "الموقع متاح",
  "emergency_location_unavailable": "الموقع غير متاح حاليًا.",
  "emergency_send_urgent_alert": "ارسال استغاثه عاجله",
  "emergency_open_card": "فتح البطاقة",
  "emergency_card_not_linked": "سيتم ربط بطاقة الطوارئ في Phase 7.",
  "emergency_direct_call": "اتصال مباشر",
  "emergency_service_unified": "الطوارئ",
  "emergency_contacts_empty_inline": "لا توجد جهات اتصال للطوارئ حتى الآن.",
  "emergency_im_safe": "أنا بخير",
  "emergency_active_load_error": "تعذر تحميل بيانات حالة الطوارئ.",
  "emergency_card_title": "بطاقة الطوارئ",
  "emergency_card_phase_placeholder": "تم اجتياز Phase 6 بنجاح.\nسيتم بناء بطاقة الطوارئ الكاملة في Phase 7.",
  "emergency_profile_setup_title": "إعداد الملف الشخصي للطوارئ",
  "emergency_profile_full_name_hint": "أدخل اسمك كما في الهوية",
  "emergency_blood_type": "فصيلة الدم",
  "emergency_select_blood_type": "اختر فصيلة الدم",
  "emergency_preferred_communication": "طريقة التواصل المفضلة",
  "emergency_communication_text": "كتابة",
  "emergency_communication_sign": "لغة إشارة",
  "emergency_communication_voice": "صوت",
  "emergency_communication_note_text": "يرجى التواصل كتابة",
  "emergency_communication_note_sign": "أستخدم لغة الإشارة",
  "emergency_communication_note_voice": "أفضل التواصل الصوتي",
  "emergency_communication_note_default": "يرجى التواصل بطريقة مناسبة",
  "emergency_important_medical_notes": "ملاحظات طبية هامة",
  "emergency_medical_notes_hint": "أي حالات طبية مزمنة أو معلومات ضرورية للمساعدة...",
  "emergency_allergies_medications": "الحساسية والأدوية",
  "emergency_allergies_hint": "قائمة بالحساسية من أطعمة أو أدوية، والأدوية الحالية...",
  "emergency_profile_local_save_notice": "يتم حفظ هذه البيانات محليًا على هذا الجهاز فقط لاستخدامها أثناء الطوارئ.",
  "emergency_vibration_alert_title": "تفعيل الاهتزاز عند التنبيه",
  "emergency_vibration_alert_subtitle": "استجابة لمسية قوية أثناء حالات الطوارئ",
  "emergency_saving": "جاري الحفظ...",
  "emergency_profile_section_title": "الملف الشخصي",
  "emergency_profile_no_data": "لا توجد بيانات ملف شخصي متاحة.",
  "emergency_medical_info_title": "المعلومات الطبية",
  "emergency_no_medical_notes": "لا توجد ملاحظات طبية مسجلة.",
  "emergency_no_allergies_medications": "لا توجد حساسية أو أدوية مسجلة.",
  "emergency_share_card": "مشاركة البطاقة",
  "emergency_card_share_subject": "بطاقة الطوارئ من قدرة",
  "emergency_profile_card_load_error": "تعذر تحميل بطاقة الطوارئ.",
  "emergency_sos_activation_title": "تفعيل الاستغاثة",
  "emergency_sos_activation_banner": "سيتم تفعيل حالة الطوارئ تلقائيًا بعد انتهاء العد التنازلي.",
  "emergency_sos_activation_countdown": "سيتم التفعيل خلال {seconds} ثوانٍ",
  "emergency_sos_activation_cancel_hint": "يمكنك الإلغاء الآن إذا تم الضغط بالخطأ.",
  "emergency_sos_activated_short": "تم التفعيل",
  "permission_location_title": "صلاحية الموقع غير\nمفعلة",
  "permission_location_subtitle": "نحتاج للوصول لموقعك الجغرافي للتمكن من مشاركته مع جهات اتصالك في حالة الطوارئ.",
  "permission_location_enabling": "جاري التفعيل...",
  "permission_location_enable": "تفعيل صلاحية الموقع",
  "permission_open_location_settings": "فتح إعدادات الموقع",
  "permission_skip_now": "تخطي الآن",
  "emergency_disability_speech": "نطقية",
  "emergency_disability_mental": "ذهنية",
  "emergency_validation_full_name": "من فضلك أدخل الاسم الكامل",
  "emergency_validation_disability_type": "من فضلك اختر نوع الإعاقة",
  "emergency_validation_blood_type": "من فضلك اختر فصيلة الدم",
  "emergency_profile_save_error": "حدث خطأ أثناء حفظ البيانات، حاول مرة أخرى.",
  "emergency_share_intro_active": "أنا في حالة طوارئ.",
  "emergency_alert_share_subject": "تنبيه طوارئ من قدرة",

  "emergency_contact_form_add_title": "إضافة جهة اتصال للطوارئ",
  "emergency_contact_form_edit_title": "تعديل جهة اتصال الطوارئ",
  "emergency_contact_name_label": "الاسم",
  "emergency_contact_relation_label": "الصفة / العلاقة",
  "emergency_contact_phone_label": "رقم الهاتف",
  "emergency_contact_name_validation": "من فضلك أدخل الاسم",
  "emergency_contact_relation_validation": "من فضلك أدخل العلاقة",
  "emergency_contact_phone_validation": "من فضلك أدخل رقم الهاتف",
  "emergency_contact_phone_invalid": "رقم الهاتف غير صالح",
  "emergency_contact_make_primary": "اجعلها جهة أساسية",
  "emergency_contact_make_primary_subtitle": "سيتم تمييزها كأول جهة اتصال للطوارئ.",
  "emergency_profile_intro_title": "معلوماتك\nالمنقذة للحياة",
  "emergency_profile_intro_subtitle": "هذه البيانات تساعد فرق الطوارئ أو مقدم الدعم المناسب للوصول إليك بسرعة وقت الحاجة.",
  "institution_no_ratings": "لا توجد تقييمات",
  "institution_no_ratings_yet": "لا توجد تقييمات بعد",
  "institution_rating_summary_compact": "{average} • {count} تقييمات",
  "institution_rating_summary_one": "{average} • {count} تقييم",
  "institution_rating_summary_many": "{average} • {count} تقييمات",
  "feedback_rating_range_error": "يجب أن يكون التقييم بين 1 و 5.",
  "feedback_user_not_logged_in": "المستخدم غير مسجل الدخول.",
  "service_working_hours": "مواعيد العمل",
  "booking_choose_suitable_time": "اختر الوقت المناسب",
  "booking_choose_day_first_for_times": "يرجى اختيار اليوم أولًا لعرض الأوقات المتاحة.",
  "booking_no_available_times_for_day": "لا توجد مواعيد متاحة في هذا اليوم.",
  "full_name_required": "الاسم الكامل مطلوب",
  "full_name_too_short": "يجب أن يكون الاسم الكامل 3 أحرف على الأقل",

  "phone_required": "رقم الهاتف مطلوب",
  "phone_invalid": "من فضلك أدخل رقم هاتف صحيح",

  "responsible_person_required": "اسم الشخص المسؤول مطلوب",
  "responsible_person_invalid": "من فضلك أدخل اسم شخص مسؤول صحيح",

  "age_required": "العمر مطلوب",

  "gender_required": "من فضلك اختر النوع",
  "disability_type_required": "من فضلك اختر نوع الإعاقة",
};