final Map<String, String> ar = {
  "welcome": "مرحباً",
  "hello": "أهلاً",
  "categories": "الفئات",
  "gender_male": "ذكر",
  "gender_female": "أنثى",
  "disability_visual": "بصري",
  "disability_hearing": "سمعي",
  "disability_physical": "حركي",
  "disability_cognitive": "معرفي",
  "disability_other": "أخرى",
  "search_hint": "ابحث عن مؤسسات أو إرشادات...",
  "quick_access": "الوصول السريع",
  "emergency_call": "مكالمة طوارئ",
  "emergency_subtitle": "احصل على مساعدة فورية",
  "intelligent": "ذكي",
  "assistant": "مساعد",
  "medical": "طبي",
  "reminders": "تذكيرات",
  "accessibility": "إمكانية الوصول",
  "guidelines": "إرشادات",
  "learn_rights": "تعلم حقوقك ونصائح",
  "recommended": "مقترح لك",
  "no_recommendations": "لا توجد اقتراحات حالياً",
  "account": "الحساب",
  "personal_info": "المعلومات الشخصية",
  "my_bookings": "حجوزاتي",
  "support": "الدعم",
  "app_guidelines": "إرشادات التطبيق",
  "feedback": "ملاحظات",
  "appearance": "المظهر",
  "light_mode": "الوضع الفاتح",
  "dark_mode": "الوضع الداكن",
  "system_default": "افتراضي النظام",
  "Language":"اللغة",
  "app_slogan": "معك لاكتشاف قدراتك",
  "disability_profile": "الملف الإعاقة",
  "edit": "تعديل",
  "disability_description":
  "تساعدنا هذه المعلومات على تخصيص ميزات الوصول لك بشكل أفضل.",
  "visual_impairment": "إعاقة بصرية",
  "low_vision_mode": "وضع ضعف الإبصار مفعل",

  "profile": "الملف الشخصي",
  "log_out": "تسجيل الخروج",
  "personal_info_title": "المعلومات الشخصية",
  "required": "مطلوب",
  "invalid_age": "أدخل عمر صحيح",
  "profile_updated": "تم تحديث البيانات بنجاح",
  "select_gender" :"اختر النوع",
  "select_disability_type" :"اختر نوع الاعاقة",

  "app_guidelines_title": "إرشادات التطبيق",
  "how_can_we_help": "كيف يمكننا المساعدة؟",
  "search_help": "ابحث عن مساعدة...",
  "all_topics": "كل المواضيع",
  "accessibility_topic": "إمكانية الوصول",
  "chatbot_topic": "المساعد الذكي",
  "health_topic": "الصحة",
  "still_need_help": "هل تحتاج مساعدة؟",
  "contact_support": "تواصل مع الدعم",

  "full_name": "الاسم الكامل",
  "email": "البريد الإلكتروني",
  "phone": "رقم الهاتف",
  "age": "العمر",
  "gender": "النوع",
  "responsible_person": "الشخص المسؤول",
  "disability_type": "نوع الإعاقة",
  "save_changes": "حفظ التعديلات",
  "support_description":  "فريق الدعم متاح على مدار 24/7 لمساعدتك في أي مشكلات تتعلق بإمكانية الوصول.",
  'Name of guardian/responsible person' : "اسم الشخص المسؤول ",
  "my_bookings": "حجوزاتي",
  "no_bookings_found": "لا توجد حجوزات حتى الآن.",
  "booking_label_date": "التاريخ",
  "booking_label_time": "الوقت",
  "booking_label_amount": "المبلغ",
  "booking_label_method": "طريقة الدفع",
  "booking_status_prefix": "الحجز",
  "payment_status_prefix": "الدفع",
  "rate_institution": "تقييم المؤسسة",
  "rating_submitted_success": "تم إرسال تقييم المؤسسة بنجاح.",

  "status_confirmed": "مؤكد",
  "status_success": "ناجح",
  "status_failed": "فاشل",
  "status_pending_payment": "في انتظار الدفع",
  "status_pending": "معلق",

  "feedback_title": "التقييم",
  "feedback_select_rating_error": "يرجى اختيار تقييم أولاً.",
  "feedback_write_comment_error": "يرجى كتابة تعليقك.",
  "feedback_submitted_success": "تم إرسال التقييم بنجاح.",
  "feedback_question": "كيف كانت تجربتك؟",
  "feedback_description": "تقييمك يساعدنا على تحسين قدرة للجميع في المجتمع.",
  "feedback_rate_section": "قيّم تجربتك",
  "feedback_comments_section": "تعليقات إضافية",
  "feedback_comment_hint": "أخبرنا المزيد عن تجربتك...\nما الذي أعجبك؟ ما الذي يمكن تحسينه؟",
  "feedback_stood_out_section": "ما الذي لفت انتباهك؟",
  "feedback_tag_fast_response": "استجابة سريعة",
  "feedback_tag_ease_of_use": "سهولة الاستخدام",
  "feedback_tag_design": "التصميم",
  "feedback_tag_support": "الدعم",
  "feedback_submit": "إرسال التقييم",
  "feedback_terms": "بالإرسال، أنت توافق على شروط الخدمة.",

  "community_feed": "المجتمع",
  "all_posts": "كل المنشورات",
  "my_posts": "منشوراتي",
  "search_posts": "البحث في المنشورات",

  "create_post_title": "إنشاء منشور",
  "post_hint": "شارك شيئاً مع المجتمع...",
  "post_empty_error": "محتوى المنشور لا يمكن أن يكون فارغاً",
  "post_too_short_error": "محتوى المنشور قصير جداً",
  "publish_post": "نشر",
  "post_published_success": "تم نشر المنشور بنجاح",
  "failed_publish_post": "فشل نشر المنشور",

  "edit_post_title": "تعديل المنشور",
  "update_post_hint": "حدّث منشورك...",
  "post_updated_success": "تم تحديث المنشور بنجاح",
  "failed_update_post": "فشل تحديث المنشور",

  "delete_post_title": "حذف المنشور",
  "delete_post_confirm": "هل أنت متأكد من حذف هذا المنشور؟",
  "post_deleted_success": "تم حذف المنشور بنجاح",
  "failed_delete_post": "فشل حذف المنشور",

  "no_posts_found": "لا توجد منشورات",
  "retry": "إعادة المحاولة",
  "cancel": "إلغاء",
  "delete": "حذف",

  "comments_title": "التعليقات",
  "no_comments": "لا توجد تعليقات بعد",
  "write_comment_hint": "اكتب تعليقاً...",
  "comment_empty_error": "التعليق لا يمكن أن يكون فارغاً",
  "comment_too_short_error": "التعليق قصير جداً",
  "comment_updated_success": "تم تحديث التعليق بنجاح",
  "comment_deleted_success": "تم حذف التعليق بنجاح",
  "failed_add_comment": "فشل إضافة التعليق",
  "failed_update_comment": "فشل تحديث التعليق",
  "failed_delete_comment": "فشل حذف التعليق",

  "edit_comment_title": "تعديل التعليق",
  "update_comment_hint": "حدّث تعليقك...",

  "delete_comment_title": "حذف التعليق",
  "delete_comment_confirm": "هل أنت متأكد من حذف هذا التعليق؟",
  "payment_method_wallet": "المحفظة",
  "payment_method_card": "بطاقة بنكية",
  "payment_method_cash": "نقداً في المؤسسة",

  "institution_title": "مراكز الدعم",
  "institution_search_hint": "ابحث عن مؤسسة...",
  "institution_details_title": "تفاصيل المؤسسة",
  "institution_address": "العنوان",
  "institution_location": "الموقع",
  "institution_phone": "الهاتف",
  "institution_email": "البريد الإلكتروني",
  "institution_not_provided": "غير متوفر",
  "institution_open_in_maps": "فتح في الخرائط",
  "institution_services_title": "الخدمات",
  "institution_no_services": "لا توجد خدمات نشطة متاحة حالياً",
  "institution_view_details": "عرض التفاصيل",
  "institution_open_location_error": "تعذّر فتح رابط الموقع.",
  "institution_rate": "تقييم المؤسسة",

  "filter_all": "الكل",
  "filter_mobility": "حركي",
  "filter_vision": "بصري",
  "filter_hearing": "سمعي",
  "filter_cognitive": "معرفي",
  "filter_other": "أخرى",

  "empty_no_match_search_filter": "لا توجد مؤسسات تطابق بحثك والفلتر المحدد",
  "empty_no_match_search_filter_subtitle": "جرّب كلمة مختلفة أو اختر فئة أخرى أو امسح الفلاتر الحالية.",
  "empty_no_match_search": "لا توجد مؤسسات تطابق بحثك",
  "empty_no_match_search_subtitle": "جرّب كلمة مختلفة أو امسح البحث لرؤية جميع المؤسسات.",
  "empty_no_match_filter": "لا توجد مؤسسات في {filter}",
  "empty_no_match_filter_subtitle": "جرّب فئة أخرى أو امسح الفلتر لرؤية جميع المؤسسات.",
  "empty_no_institutions": "لا توجد مؤسسات",
  "empty_no_institutions_subtitle": "يرجى المحاولة مرة أخرى لاحقاً.",
  "clear_filters": "مسح الفلاتر",

  "results_showing_all_one": "عرض {count} مؤسسة",
  "results_showing_all_many": "عرض {count} مؤسسات",
  "results_showing_query_one": "عرض {count} نتيجة لـ \"{query}\"",
  "results_showing_query_many": "عرض {count} نتائج لـ \"{query}\"",
  "results_showing_filter_one": "عرض {count} مؤسسة في {filter}",
  "results_showing_filter_many": "عرض {count} مؤسسات في {filter}",
  "results_showing_both_one": "عرض {count} نتيجة لـ \"{query}\" في {filter}",
  "results_showing_both_many": "عرض {count} نتائج لـ \"{query}\" في {filter}",

  "service_free": "مجاني",
  "service_book_now": "احجز الآن",

      "recommended": "موصى به لك",
"no_recommendations": "لا توجد توصيات.",
"no_recommendations_available": "لا تتوفر توصيات في الوقت الحالي.",
"categories": "الفئات",
"physical": "حركي",
"visual": "بصري",
"hearing": "سمعي",


    "rate_institution": "تقييم المؤسسة",
"select_your_rating": "اختر تقييمك",
"your_rating": "تقييمك: {} / 5",
"please_select_rating": "من فضلك اختر تقييم أولاً",
"cancel": "إلغاء",
"submit": "إرسال",
"save_rating": "حفظ التقييم",

  "booking_card_payment_title": "الدفع بالبطاقة",
  "booking_card_info": "عند الضغط على الدفع، سيتم فتح صفحة الدفع التجريبية من Paymob لإتمام الدفع بالبطاقة بأمان.",
  "booking_pay_with_card": "الدفع بالبطاقة",
  "booking_checkout_error": "تعذّر فتح صفحة الدفع.",

  "booking_cash_title": "الدفع نقداً في المؤسسة",
  "booking_cash_info": "سيتم تأكيد حجزك فوراً، وسيتم تحصيل المبلغ في المؤسسة.",
  "booking_confirm": "تأكيد الحجز",

  "booking_checkout_title": "حجز الخدمة",
  "booking_select_datetime_error": "يرجى تحديد التاريخ والوقت أولاً.",
  "booking_continue_to_payment": "المتابعة للدفع",

  "booking_payment_method_title": "طريقة الدفع",
  "booking_choose_method": "اختر طريقة الدفع",
  "booking_method_card_title": "بطاقة بنكية",
  "booking_method_card_subtitle": "ادفع بأمان عبر صفحة Paymob التجريبية.",
  "booking_method_wallet_title": "محفظة إلكترونية",
  "booking_method_wallet_subtitle": "ادفع باستخدام محفظة جوال مدعومة عبر Paymob.",
  "booking_method_cash_title": "نقداً في المؤسسة",
  "booking_method_cash_subtitle": "أكّد الحجز الآن وادفع عند الحضور.",
  "booking_continue": "متابعة",

  "booking_wallet_title": "الدفع بالمحفظة",
  "booking_wallet_info": "عند الضغط على الدفع، سيتم فتح صفحة Paymob التجريبية لإتمام عملية الدفع بالمحفظة.",
  "booking_pay_with_wallet": "الدفع بالمحفظة",

  "booking_processing_title": "جارٍ المعالجة",
  "booking_processing_checking": "جارٍ التحقق من نتيجة الدفع...",
  "booking_processing_description": "يرجى الانتظار بينما نتحقق من حجزك مع Paymob ونحدّث الحالة النهائية.",

  "booking_result_title": "نتيجة الحجز",
  "booking_result_not_found_title": "الحجز غير موجود",
  "booking_result_not_found_message": "تعذّر تحميل هذا الحجز في الوقت الحالي.",
  "booking_result_confirmed_title": "تم تأكيد الحجز",
  "booking_result_confirmed_message": "تم تأكيد حجزك بنجاح.",
  "booking_result_processing_title": "لا تزال المعالجة جارية",
  "booking_result_processing_message": "عدت إلى التطبيق، لكن لم يكتمل التحديث النهائي بعد. يمكنك التحقق مجدداً من الصفحة الرئيسية.",
  "booking_result_cancelled_title": "تم إلغاء الحجز",
  "booking_result_cancelled_message": "تم إلغاء جلسة الدفع أو إبطالها.",
  "booking_result_failed_title": "فشل الحجز",
  "booking_result_failed_message": "لم تكتمل عملية الدفع بنجاح.",
  "booking_result_load_error": "تعذّر تحميل نتيجة الحجز في الوقت الحالي.",
  "booking_result_back_home": "العودة إلى الرئيسية",
  "booking_result_label_id": "رقم الحجز",
  "booking_result_label_booking_status": "حالة الحجز",
  "booking_result_label_payment_method": "طريقة الدفع",
  "booking_result_label_payment_status": "حالة الدفع",
  "booking_result_label_date": "التاريخ المطلوب",
  "booking_result_label_time": "الوقت المطلوب",
  "booking_result_unknown": "غير معروف",

  "booking_datetime_section_title": "تفاصيل الحجز",
  "booking_preferred_date": "التاريخ المفضّل",
  "booking_preferred_time": "الوقت المفضّل",
  "booking_select_date": "اختر تاريخاً",
  "booking_select_time": "اختر وقتاً",

      "booking_summary_category": "الفئة",
"booking_summary_price": "السعر",
"booking_summary_duration": "المدة",
"booking_summary_date": "التاريخ",
"booking_summary_time": "الوقت",
"booking_summary_notes": "ملاحظات",
"booking_summary_not_selected": "لم يتم الاختيار",
"booking_summary_no_notes": "لا توجد ملاحظات إضافية",
"booking_notes_title": "ملاحظات إضافية",
"booking_notes_hint": "أضف أي ملاحظات أو تفاصيل للمؤسسة..."

};