final Map<String, String> ar = {
  "welcome": "مرحباً",
  "hello": "أهلاً",
  "categories": "الفئات",
  "gender_male": "ذكر",
  "gender_female": "أنثى",
  "disability_visual": "بصري",
  "disability_hearing": "سمعي",
  "disability_physical": "حركي",
  "disability_cognitive": "معرفي",
  "disability_other": "أخرى",
  "search_hint": "ابحث عن مؤسسات أو إرشادات...",
  "quick_access": "الوصول السريع",
  "emergency_call": "مكالمة طوارئ",
  "emergency_subtitle": "احصل على مساعدة فورية",
  "intelligent": "ذكي",
  "assistant": "مساعد",
  "medical": "طبي",
  "reminders": "تذكيرات",
  "accessibility": "إمكانية الوصول",
  "guidelines": "إرشادات",
  "learn_rights": "تعلم حقوقك ونصائح",
  "recommended": "مقترح لك",
  "no_recommendations": "لا توجد اقتراحات حالياً",
  "account": "الحساب",
  "personal_info": "المعلومات الشخصية",
  "my_bookings": "حجوزاتي",
  "support": "الدعم",
  "app_guidelines": "إرشادات التطبيق",
  "feedback": "ملاحظات",
  "appearance": "المظهر",
  "light_mode": "الوضع الفاتح",
  "dark_mode": "الوضع الداكن",
  "system_default": "افتراضي النظام",
  "Language":"اللغة",
  "app_slogan": "معك لاكتشاف قدراتك",
  "disability_profile": "الملف الإعاقة",
  "edit": "تعديل",
  "disability_description":
  "تساعدنا هذه المعلومات على تخصيص ميزات الوصول لك بشكل أفضل.",
  "visual_impairment": "إعاقة بصرية",
  "low_vision_mode": "وضع ضعف الإبصار مفعل",

  "profile": "الملف الشخصي",
  "log_out": "تسجيل الخروج",
  "personal_info_title": "المعلومات الشخصية",
  "required": "مطلوب",
  "invalid_age": "أدخل عمر صحيح",
  "profile_updated": "تم تحديث البيانات بنجاح",
  "select_gender" :"اختر النوع",
  "select_disability_type" :"اختر نوع الاعاقة",

  "app_guidelines_title": "إرشادات التطبيق",
  "how_can_we_help": "كيف يمكننا المساعدة؟",
  "search_help": "ابحث عن مساعدة...",
  "all_topics": "كل المواضيع",
  "accessibility_topic": "إمكانية الوصول",
  "chatbot_topic": "المساعد الذكي",
  "health_topic": "الصحة",
  "still_need_help": "هل تحتاج مساعدة؟",
  "contact_support": "تواصل مع الدعم",

  "full_name": "الاسم الكامل",
  "email": "البريد الإلكتروني",
  "phone": "رقم الهاتف",
  "age": "العمر",
  "gender": "النوع",
  "responsible_person": "الشخص المسؤول",
  "disability_type": "نوع الإعاقة",
  "save_changes": "حفظ التعديلات",
  "support_description":  "فريق الدعم متاح على مدار 24/7 لمساعدتك في أي مشكلات تتعلق بإمكانية الوصول.",
  'Name of guardian/responsible person' : "اسم الشخص المسؤول ",
  "my_bookings": "حجوزاتي",
  "no_bookings_found": "لا توجد حجوزات حتى الآن.",
  "booking_label_date": "التاريخ",
  "booking_label_time": "الوقت",
  "booking_label_amount": "المبلغ",
  "booking_label_method": "طريقة الدفع",
  "booking_status_prefix": "الحجز",
  "payment_status_prefix": "الدفع",
  "rate_institution": "تقييم المؤسسة",
  "rating_submitted_success": "تم إرسال تقييم المؤسسة بنجاح.",

  "status_confirmed": "مؤكد",
  "status_success": "ناجح",
  "status_failed": "فاشل",
  "status_pending_payment": "في انتظار الدفع",
  "status_pending": "معلق",

  "feedback_title": "التقييم",
  "feedback_select_rating_error": "يرجى اختيار تقييم أولاً.",
  "feedback_write_comment_error": "يرجى كتابة تعليقك.",
  "feedback_submitted_success": "تم إرسال التقييم بنجاح.",
  "feedback_question": "كيف كانت تجربتك؟",
  "feedback_description": "تقييمك يساعدنا على تحسين قدرة للجميع في المجتمع.",
  "feedback_rate_section": "قيّم تجربتك",
  "feedback_comments_section": "تعليقات إضافية",
  "feedback_comment_hint": "أخبرنا المزيد عن تجربتك...\nما الذي أعجبك؟ ما الذي يمكن تحسينه؟",
  "feedback_stood_out_section": "ما الذي لفت انتباهك؟",
  "feedback_tag_fast_response": "استجابة سريعة",
  "feedback_tag_ease_of_use": "سهولة الاستخدام",
  "feedback_tag_design": "التصميم",
  "feedback_tag_support": "الدعم",
  "feedback_submit": "إرسال التقييم",
  "feedback_terms": "بالإرسال، أنت توافق على شروط الخدمة.",

  "community_feed": "المجتمع",
  "all_posts": "كل المنشورات",
  "my_posts": "منشوراتي",
  "search_posts": "البحث في المنشورات",

  "create_post_title": "إنشاء منشور",
  "post_hint": "شارك شيئاً مع المجتمع...",
  "post_empty_error": "محتوى المنشور لا يمكن أن يكون فارغاً",
  "post_too_short_error": "محتوى المنشور قصير جداً",
  "publish_post": "نشر",
  "post_published_success": "تم نشر المنشور بنجاح",
  "failed_publish_post": "فشل نشر المنشور",

  "edit_post_title": "تعديل المنشور",
  "update_post_hint": "حدّث منشورك...",
  "post_updated_success": "تم تحديث المنشور بنجاح",
  "failed_update_post": "فشل تحديث المنشور",

  "delete_post_title": "حذف المنشور",
  "delete_post_confirm": "هل أنت متأكد من حذف هذا المنشور؟",
  "post_deleted_success": "تم حذف المنشور بنجاح",
  "failed_delete_post": "فشل حذف المنشور",

  "no_posts_found": "لا توجد منشورات",
  "retry": "إعادة المحاولة",
  "cancel": "إلغاء",
  "delete": "حذف",

  "comments_title": "التعليقات",
  "no_comments": "لا توجد تعليقات بعد",
  "write_comment_hint": "اكتب تعليقاً...",
  "comment_empty_error": "التعليق لا يمكن أن يكون فارغاً",
  "comment_too_short_error": "التعليق قصير جداً",
  "comment_updated_success": "تم تحديث التعليق بنجاح",
  "comment_deleted_success": "تم حذف التعليق بنجاح",
  "failed_add_comment": "فشل إضافة التعليق",
  "failed_update_comment": "فشل تحديث التعليق",
  "failed_delete_comment": "فشل حذف التعليق",

  "edit_comment_title": "تعديل التعليق",
  "update_comment_hint": "حدّث تعليقك...",

  "delete_comment_title": "حذف التعليق",
  "delete_comment_confirm": "هل أنت متأكد من حذف هذا التعليق؟",
  "payment_method_wallet": "المحفظة",
  "payment_method_card": "بطاقة بنكية",
  "payment_method_cash": "نقداً في المؤسسة"
};