final Map<String, String> en = {
  "welcome": "Welcome",
  "hello": "Hello",
  "categories": "Categories",
  "gender_male": "Male",
  "gender_female": "Female",
  "disability_visual": "Visual",
  "disability_hearing": "Hearing",
  "disability_physical": "Physical",
  "disability_cognitive": "Cognitive",
  "disability_other": "Other",
  "search_hint": "Search institutions or guidelines...",
  "quick_access": "Quick Access",
  "emergency_call": "Emergency Call",
  "emergency_subtitle": "Get immediate assistance",
  "intelligent": "Intelligent",
  "assistant": "Assistant",
  "medical": "Medical",
  "reminders": "Reminders",
  "accessibility": "Accessibility",
  "guidelines": "Guidelines",
  "learn_rights": "Learn your rights & tips",
  "recommended": "Recommended For You",
  "no_recommendations": "No recommendations available right now",
  "account": "Account",
  "personal_info": "Personal Info",
  "my_bookings": "My Bookings",
  "support": "Support",
  "app_guidelines": "App Guidelines",
  "feedback": "Feedback",
  "appearance": "Appearance",
  "light_mode": "Light Mode",
  "dark_mode": "Dark Mode",
  "system_default": "System Default",
  "Language" : "Language",
  "app_slogan": "«With you to discover your ability»",
  "disability_profile": "Disability Profile",
  "edit": "Edit",
  "disability_description":
  "This information helps us tailor accessibility features specifically for you.",
  "visual_impairment": "Visual Impairment",
  "low_vision_mode": "Low vision mode active",

  "profile": "Profile",
  "log_out": "Log Out",
  "personal_info_title": "Personal Info",
  "required": "is required",
  "invalid_age": "Enter a valid age",
  "profile_updated": "Profile updated successfully",
  "select_gender" : "Select gender",
  "select_disability_type" :"Select disability type",


  "app_guidelines_title": "App Guidelines",
  "how_can_we_help": "How can we help?",
  "search_help": "Search for help...",
  "all_topics": "All Topics",
  "accessibility_topic": "Accessibility",
  "chatbot_topic": "Chatbot",
  "health_topic": "Health",
  "still_need_help": "Still need help?",
  "contact_support": "Contact Support",

  "full_name": "Full Name",
  "email": "Email Address",
  "phone": "Phone Number",
  "age": "Age",
  "gender": "Gender",
  "responsible_person": "Responsible Person",
  "disability_type": "Disability Type",
  "save_changes": "Save Changes",
  'Name of guardian/responsible person' : "Name of guardian/responsible person",
  "support_description": "Our support team is available 24/7 to assist you with any accessibility concerns.",

  "my_bookings": "My Bookings",
  "no_bookings_found": "No bookings found yet.",
  "booking_label_date": "Date",
  "booking_label_time": "Time",
  "booking_label_amount": "Amount",
  "booking_label_method": "Method",
  "booking_status_prefix": "Booking",
  "payment_status_prefix": "Payment",
  "rate_institution": "Rate Institution",
  "rating_submitted_success": "Institution rating submitted successfully.",

  "status_confirmed": "Confirmed",
  "status_success": "Success",
  "status_failed": "Failed",
  "status_pending_payment": "Pending Payment",
  "status_pending": "Pending",

  "feedback_title": "Feedback",
  "feedback_select_rating_error": "Please select a rating first.",
  "feedback_write_comment_error": "Please write your feedback comment.",
  "feedback_submitted_success": "Feedback submitted successfully.",
  "feedback_question": "How was your experience?",
  "feedback_description": "Your feedback helps us improve Qudra for everyone in the community.",
  "feedback_rate_section": "RATE YOUR EXPERIENCE",
  "feedback_comments_section": "ADDITIONAL COMMENTS",
  "feedback_comment_hint": "Tell us more about your experience...\nWhat did you like? What can we\nimprove?",
  "feedback_stood_out_section": "WHAT STOOD OUT?",
  "feedback_tag_fast_response": "Fast Response",
  "feedback_tag_ease_of_use": "Ease of Use",
  "feedback_tag_design": "Design",
  "feedback_tag_support": "Support",
  "feedback_submit": "Submit Feedback",
  "feedback_terms": "By submitting, you agree to our Terms of Service.",

  "community_feed": "Community Feed",
  "all_posts": "All Posts",
  "my_posts": "My Posts",
  "search_posts": "Search posts",

  "create_post_title": "Create Post",
  "post_hint": "Share something with the community...",
  "post_empty_error": "Post content cannot be empty",
  "post_too_short_error": "Post content is too short",
  "publish_post": "Publish Post",
  "post_published_success": "Post published successfully",
  "failed_publish_post": "Failed to publish post",

  "edit_post_title": "Edit Post",
  "update_post_hint": "Update your post...",
  "post_updated_success": "Post updated successfully",
  "failed_update_post": "Failed to update post",

  "delete_post_title": "Delete Post",
  "delete_post_confirm": "Are you sure you want to delete this post?",
  "post_deleted_success": "Post deleted successfully",
  "failed_delete_post": "Failed to delete post",

  "no_posts_found": "No posts found",
  "retry": "Retry",
  "cancel": "Cancel",
  "delete": "Delete",

  "comments_title": "Comments",
  "no_comments": "No comments yet",
  "write_comment_hint": "Write a comment...",
  "comment_empty_error": "Comment cannot be empty",
  "comment_too_short_error": "Comment is too short",
  "comment_updated_success": "Comment updated successfully",
  "comment_deleted_success": "Comment deleted successfully",
  "failed_add_comment": "Failed to add comment",
  "failed_update_comment": "Failed to update comment",
  "failed_delete_comment": "Failed to delete comment",

  "edit_comment_title": "Edit Comment",
  "update_comment_hint": "Update your comment...",

  "delete_comment_title": "Delete Comment",
  "delete_comment_confirm": "Are you sure you want to delete this comment?",


  "payment_method_wallet": "Wallet",
"payment_method_card": "Card",
"payment_method_cash": "Cash at Institution"
};