final Map<String, String> en = {
  "welcome": "Welcome",
  "hello": "Hello",
  "categories": "Categories",
  "physical": "Physical",
  "visual": "Visual",
  "hearing": "Hearing",
  "search_hint": "Search institutions or guidelines...",
  "quick_access": "Quick Access",
  "emergency_call": "Emergency Call",
  "emergency_subtitle": "Get immediate assistance",
  "intelligent": "Intelligent",
  "assistant": "Assistant",
  "medical": "Medical",
  "reminders": "Reminders",
  "accessibility": "Accessibility",
  "guidelines": "Guidelines",
  "learn_rights": "Learn your rights & tips",
  "recommended": "Recommended For You",
  "no_recommendations": "No recommendations available right now",
  "account": "Account",
  "personal_info": "Personal Info",
  "my_bookings": "My Bookings",
  "support": "Support",
  "app_guidelines": "App Guidelines",
  "feedback": "Feedback",
  "appearance": "Appearance",
  "light_mode": "Light Mode",
  "dark_mode": "Dark Mode",
  "system_default": "System Default",
  "app_slogan": "«With you to discover your ability»",
  "disability_profile": "Disability Profile",
  "edit": "Edit",
  "disability_description":
  "This information helps us tailor accessibility features specifically for you.",
  "visual_impairment": "Visual Impairment",
  "low_vision_mode": "Low vision mode active",

  "profile": "Profile",
  "log_out": "Log Out",
  "personal_info_title": "Personal Info",

  "app_guidelines_title": "App Guidelines",
  "how_can_we_help": "How can we help?",
  "search_help": "Search for help...",
  "all_topics": "All Topics",
  "accessibility_topic": "Accessibility",
  "chatbot_topic": "Chatbot",
  "health_topic": "Health",
  "still_need_help": "Still need help?",
  "contact_support": "Contact Support",

  "full_name": "Full Name",
  "email": "Email Address",
  "phone": "Phone Number",
  "age": "Age",
  "gender": "Gender",
  "responsible_person": "Responsible Person",
  "disability_type": "Disability Type",
  "save_changes": "Save Changes",

  "support_description": "Our support team is available 24/7 to assist you with any accessibility concerns.",
};