final Map<String, String> en = <String, String>{
  "welcome": "Welcome",
  "hello": "Hello",
  "categories": "Categories",
  "gender_male": "Male",
  "gender_female": "Female",
  "disability_visual": "Visual",
  "disability_hearing": "Hearing",
  "disability_physical": "Physical",
  "disability_cognitive": "Cognitive",
  "disability_other": "Other",
  "search_hint": "Search institutions or guidelines...",
  "quick_access": "Quick Access",
  "emergency_call": "Emergency Call",
  "emergency_subtitle": "Get immediate assistance",
  "intelligent": "Intelligent",
  "assistant": "Assistant",
  "medical": "Medical",
  "reminders": "Reminders",
  "accessibility": "Accessibility",
  "guidelines": "Guidelines",
  "learn_rights": "Learn your rights & tips",
  "recommended": "Recommended For You",
  "no_recommendations": "No recommendations available right now",
  "account": "Account",
  "personal_info": "Personal Info",
  "my_bookings": "My Bookings",
  "support": "Support",
  "app_guidelines": "App Guidelines",
  "feedback": "Feedback",
  "appearance": "Appearance",
  "light_mode": "Light Mode",
  "dark_mode": "Dark Mode",
  "system_default": "System Default",
  "Language" : "Language",
  "app_slogan": "«With you to discover your ability»",
  "disability_profile": "Disability Profile",
  "edit": "Edit",
  "disability_description":
  "This information helps us tailor accessibility features specifically for you.",
  "visual_impairment": "Visual Impairment",
  "low_vision_mode": "Low vision mode active",

  "profile": "Profile",
  "log_out": "Log Out",
  "personal_info_title": "Personal Info",
  "required": "is required",
  "invalid_age": "Enter a valid age",
  "profile_updated": "Profile updated successfully",
  "select_gender" : "Select gender",
  "select_disability_type" :"Select disability type",


  "app_guidelines_title": "App Guidelines",
  "how_can_we_help": "How can we help?",
  "search_help": "Search for help...",
  "all_topics": "All Topics",
  "accessibility_topic": "Accessibility",
  "chatbot_topic": "Chatbot",
  "health_topic": "Health",
  "still_need_help": "Still need help?",
  "contact_support": "Contact Support",

  "full_name": "Full Name",
  "email": "Email Address",
  "phone": "Phone Number",
  "age": "Age",
  "gender": "Gender",
  "responsible_person": "Responsible Person",
  "disability_type": "Disability Type",
  "save_changes": "Save Changes",
  'Name of guardian/responsible person' : "Name of guardian/responsible person",
  "support_description": "Our support team is available 24/7 to assist you with any accessibility concerns.",

  "my_bookings": "My Bookings",
  "no_bookings_found": "No bookings found yet.",
  "booking_label_date": "Date",
  "booking_label_time": "Time",
  "booking_label_amount": "Amount",
  "booking_label_method": "Method",
  "booking_status_prefix": "Booking",
  "payment_status_prefix": "Payment",
  "rate_institution": "Rate Institution",
  "rating_submitted_success": "Institution rating submitted successfully.",

  "status_confirmed": "Confirmed",
  "status_success": "Success",
  "status_failed": "Failed",
  "status_pending_payment": "Pending Payment",
  "status_pending": "Pending",

  "feedback_title": "Feedback",
  "feedback_select_rating_error": "Please select a rating first.",
  "feedback_write_comment_error": "Please write your feedback comment.",
  "feedback_submitted_success": "Feedback submitted successfully.",
  "feedback_question": "How was your experience?",
  "feedback_description": "Your feedback helps us improve Qudra for everyone in the community.",
  "feedback_rate_section": "RATE YOUR EXPERIENCE",
  "feedback_comments_section": "ADDITIONAL COMMENTS",
  "feedback_comment_hint": "Tell us more about your experience...\nWhat did you like? What can we\nimprove?",
  "feedback_stood_out_section": "WHAT STOOD OUT?",
  "feedback_tag_fast_response": "Fast Response",
  "feedback_tag_ease_of_use": "Ease of Use",
  "feedback_tag_design": "Design",
  "feedback_tag_support": "Support",
  "feedback_submit": "Submit Feedback",
  "feedback_terms": "By submitting, you agree to our Terms of Service.",

  "community_feed": "Community Feed",
  "all_posts": "All Posts",
  "my_posts": "My Posts",
  "search_posts": "Search posts",

  "create_post_title": "Create Post",
  "post_hint": "Share something with the community...",
  "post_empty_error": "Post content cannot be empty",
  "post_too_short_error": "Post content is too short",
  "publish_post": "Publish Post",
  "post_published_success": "Post published successfully",
  "failed_publish_post": "Failed to publish post",

  "edit_post_title": "Edit Post",
  "update_post_hint": "Update your post...",
  "post_updated_success": "Post updated successfully",
  "failed_update_post": "Failed to update post",

  "delete_post_title": "Delete Post",
  "delete_post_confirm": "Are you sure you want to delete this post?",
  "post_deleted_success": "Post deleted successfully",
  "failed_delete_post": "Failed to delete post",

  "no_posts_found": "No posts found",
  "retry": "Retry",
  "cancel": "Cancel",
  "delete": "Delete",

  "comments_title": "Comments",
  "no_comments": "No comments yet",
  "write_comment_hint": "Write a comment...",
  "comment_empty_error": "Comment cannot be empty",
  "comment_too_short_error": "Comment is too short",
  "comment_updated_success": "Comment updated successfully",
  "comment_deleted_success": "Comment deleted successfully",
  "failed_add_comment": "Failed to add comment",
  "failed_update_comment": "Failed to update comment",
  "failed_delete_comment": "Failed to delete comment",

  "edit_comment_title": "Edit Comment",
  "update_comment_hint": "Update your comment...",

  "delete_comment_title": "Delete Comment",
  "delete_comment_confirm": "Are you sure you want to delete this comment?",


  "payment_method_wallet": "Wallet",
  "payment_method_card": "Card",
  "payment_method_cash": "Cash at Institution",

  "institution_title": "Support Centers",
  "institution_search_hint": "Search institutions...",
  "institution_details_title": "Institution Details",
  "institution_address": "Address",
  "institution_location": "Location",
  "institution_phone": "Phone",
  "institution_email": "Email",
  "institution_not_provided": "Not provided",
  "institution_open_in_maps": "Open in Maps",
  "institution_services_title": "Services",
  "institution_no_services": "No active services available right now",
  "institution_view_details": "View Details",
  "institution_open_location_error": "Unable to open the location link.",
  "institution_rate": "Rate Institution",

  "filter_all": "All",
  "filter_mobility": "Mobility",
  "filter_vision": "Vision",
  "filter_hearing": "Hearing",
  "filter_cognitive": "Cognitive",
  "filter_other": "Other",

  "empty_no_match_search_filter": "No institutions match your search and filter",
  "empty_no_match_search_filter_subtitle": "Try a different keyword, choose another category, or clear the current filters.",
  "empty_no_match_search": "No institutions match your search",
  "empty_no_match_search_subtitle": "Try a different keyword or clear the current search to see all institutions.",
  "empty_no_match_filter": "No institutions found in {filter}",
  "empty_no_match_filter_subtitle": "Try another category or clear the current filter to see all institutions.",
  "empty_no_institutions": "No institutions found",
  "empty_no_institutions_subtitle": "Please check again later.",
  "clear_filters": "Clear Filters",

  "results_showing_all_one": "Showing {count} institution",
  "results_showing_all_many": "Showing {count} institutions",
  "results_showing_query_one": "Showing {count} result for \"{query}\"",
  "results_showing_query_many": "Showing {count} results for \"{query}\"",
  "results_showing_filter_one": "Showing {count} institution in {filter}",
  "results_showing_filter_many": "Showing {count} institutions in {filter}",
  "results_showing_both_one": "Showing {count} result for \"{query}\" in {filter}",
  "results_showing_both_many": "Showing {count} results for \"{query}\" in {filter}",

  "service_free": "Free",
  "service_book_now": "Book Now",
  "recommended": "Recommended for You",
  "no_recommendations": "No recommendations found.",
  "no_recommendations_available": "No recommendations available right now.",
  "categories": "Categories",
  "physical": "Physical",
  "visual": "Visual",
  "hearing": "Hearing",

  "rate_institution": "Rate Institution",
  "select_your_rating": "Select your rating",
  "your_rating": "Your rating: {} / 5",
  "please_select_rating": "Please select a rating first.",
  "cancel": "Cancel",
  "submit": "Submit",
  "save_rating": "Save Rating",

  "booking_card_payment_title": "Card Payment",
  "booking_card_info": "When you press pay, Paymob test checkout will open so you can complete the card payment securely.",
  "booking_pay_with_card": "Pay with Card",
  "booking_checkout_error": "Could not open the payment checkout page.",

  "booking_cash_title": "Cash at Institution",
  "booking_cash_info": "Your booking will be confirmed immediately, and payment will be collected at the institution.",
  "booking_confirm": "Confirm Booking",

  "booking_checkout_title": "Book Service",
  "booking_select_datetime_error": "Please select both date and time first.",
  "booking_continue_to_payment": "Continue to Payment",

  "booking_payment_method_title": "Payment Method",
  "booking_choose_method": "Choose Payment Method",
  "booking_method_card_title": "Card",
  "booking_method_card_subtitle": "Pay securely using Paymob test checkout.",
  "booking_method_wallet_title": "Wallet",
  "booking_method_wallet_subtitle": "Pay using a supported mobile wallet via Paymob.",
  "booking_method_cash_title": "Cash at Institution",
  "booking_method_cash_subtitle": "Confirm the booking now and pay at the institution.",
  "booking_continue": "Continue",

  "booking_wallet_title": "Wallet Payment",
  "booking_wallet_info": "When you press pay, Paymob test checkout will open so you can continue with the wallet payment flow.",
  "booking_pay_with_wallet": "Pay with Wallet",

  "booking_processing_title": "Processing",
  "booking_processing_checking": "Checking payment result...",
  "booking_processing_description": "Please wait while we verify your booking with Paymob and refresh the final booking status.",

  "booking_result_title": "Booking Result",
  "booking_result_not_found_title": "Booking Not Found",
  "booking_result_not_found_message": "We could not load this booking right now.",
  "booking_result_confirmed_title": "Booking Confirmed",
  "booking_result_confirmed_message": "Your booking was confirmed successfully.",
  "booking_result_processing_title": "Still Processing",
  "booking_result_processing_message": "Paymob has returned you to the app, but the final callback has not finished updating the booking yet. You can check again shortly from Home.",
  "booking_result_cancelled_title": "Booking Cancelled",
  "booking_result_cancelled_message": "The payment session was cancelled or voided.",
  "booking_result_failed_title": "Booking Failed",
  "booking_result_failed_message": "The payment was not completed successfully.",
  "booking_result_load_error": "Could not load booking result right now.",
  "booking_result_back_home": "Back to Home",
  "booking_result_label_id": "Booking ID",
  "booking_result_label_booking_status": "Booking Status",
  "booking_result_label_payment_method": "Payment Method",
  "booking_result_label_payment_status": "Payment Status",
  "booking_result_label_date": "Requested Date",
  "booking_result_label_time": "Requested Time",
  "booking_result_unknown": "Unknown",

  "booking_datetime_section_title": "Booking Details",
  "booking_preferred_date": "Preferred Date",
  "booking_preferred_time": "Preferred Time",
  "booking_select_date": "Select a date",
  "booking_select_time": "Select a time",

  "booking_summary_category": "Category",
  "booking_summary_price": "Price",
  "booking_summary_duration": "Duration",
  "booking_summary_date": "Date",
  "booking_summary_time": "Time",
  "booking_summary_notes": "Notes",
  "booking_summary_not_selected": "Not selected",
  "booking_summary_no_notes": "No additional notes",
  "booking_notes_title": "Additional Notes",
  "booking_notes_hint": "Add any notes or details for the institution...",

      "emergency_help": "Emergency help",
"nearby_institutions": "Nearby institutions",
"accessible_transport": "Accessible transport",
"my_rights": "My rights",

"type_message": "Type a message...",
"you": "You",
"ai_name": "Qudra AI",
"online": "ONLINE",
"clear_chat": "Clear chat",
"app_name_ai": "Qudra AI",


  "medical_reminders": "Medical Reminders",
  "today_progress": "Today's Progress",
  "doses_completed": "Doses completed",
  "daily_reminders": "Daily Reminders",
  "no_reminders": "No reminders yet. Tap + to add one.",

  "taken": "Taken",
  "swipe": "Swipe",
  "skip": "Skip",

  "missed": "missed",
  "next_at": "Next at",
  "no_doses_scheduled": "No doses scheduled",
  "all_doses_completed": "All doses completed",
  "no_upcoming_doses": "No upcoming doses",

  "delete_reminder": "Delete Reminder?",
  "delete": "Delete",
  "cancel": "Cancel",

  "add_reminder": "Add Reminder",
  "medicine_name": "Medicine Name",
  "dose_notes": "Dose / Notes",
  "enter_medicine_name": "Please enter medicine name",
  "enter_dose_notes": "Please enter dose / notes",
  "pick_time": "Pick Time",
  "choose_time": "Please choose a reminder time",
  "save": "Save",


  "medical_reminders": "Medical Reminders",
  "today_progress": "Today's Progress",
  "doses_completed": "Doses completed",
  "daily_reminders": "Daily Reminders",
  "no_reminders": "No reminders yet. Tap + to add one.",
  "taken": "Taken",
  "swipe": "Swipe",
  "skip": "Skip",
  "missed": "missed",
  "next_at": "Next at",
  "no_doses_scheduled": "No doses scheduled",
  "all_doses_completed": "All doses completed",
  "no_upcoming_doses": "No upcoming doses",
  "delete_reminder": "Delete Reminder?",
  "delete": "Delete",
  "cancel": "Cancel",
  "add_reminder": "Add Reminder",
  "medicine_name": "Medicine Name",
  "dose_notes": "Dose / Notes",
  "enter_medicine_name": "Please enter medicine name",
  "enter_dose_notes": "Please enter dose / notes",
  "pick_time": "Pick Time",
  "choose_time": "Please choose a reminder time",
  "save": "Save",
  "accessibility_hub": "Accessibility Hub",
  "search_hint_a11y": "Search rights, tips, resources...",
  "filter_all": "All",
  "filter_popular": "Popular",
  "category_visual": "Visual",
  "category_hearing": "Hearing",
  "category_physical": "Physical",
  "category_cognitive": "Cognitive",
  "category_other": "Other",
  "subtitle_visual": "Blindness, Low Vision, Color Blindness",
  "subtitle_hearing": "Deafness, Hard of Hearing, Sign Language",
  "subtitle_physical": "Mobility, Motor Disability, Wheelchair",
  "subtitle_cognitive": "Learning Disabilities, Neurodiversity",
  "subtitle_other": "Speech, Invisible Disabilities",
  "items_label": "items",
  "no_resources": "No resources yet",
  "no_resources_category": "No resources in this category",
  "no_resources_found": "No resources found",
  "retry": "Retry",

  'sign_up': 'Sign Up',
'log_in': 'Log In',
'sign_in': 'Sign In',
'login': 'Login',

'create_account': 'Create Account',
'join_qudra': 'Join Qudra to access tailored services',
'fill_all_fields': 'Please fill all fields',
'account_created': 'Account created successfully!',

'full_name': 'Full Name',
'full_name_hint': 'Enter your full name',
'phone_number': 'Phone Number',
'phone_hint': 'e.g. 01234567890',
'email_address': 'Email Address',
'email_hint': 'name@example.com',
'password': 'Password',
'password_hint': 'Min. 8 characters',
'responsible_person': 'Responsible Person Name',
'responsible_hint': 'Name of guardian',
'age': 'Age',
'age_hint': 'e.g. 25',
'gender': 'Gender',
'select': 'Select',
'disability_type_label': 'Disability Type',
'select_type': 'Select your type',
'gender_male': 'Male',
'gender_female': 'Female',
'already_have_account': 'Already have an account?',
'no_account': "Don't have an account?",

'tagline': '\"With you to discover your ability\"',
'welcome_back': 'Welcome back',
'email_required': 'Email is required',
'email_invalid': 'Enter a valid email',
'forgot_password_btn': 'Forgot Password?',

'forgot_password_title': 'Forgot Password',
'reset_password_heading': 'Reset your\npassword',
'reset_password_desc': "Enter the email address associated with your account. We'll send you a secure link to reset your password.",
'email_note': 'Make sure this is the email you signed up with.',
'reset_password_btn': 'Reset Password',
'remember_password': 'Remember your password?',

'reset_password_title': 'Reset Password',
'reset_password_instruction': 'Enter the verification code sent to your email and choose your new password.',
'verification_token': 'Verification Token',
'token_hint': 'Enter token',
'token_required': 'Token is required',
'password_required': 'Password is required',
'min_6_chars': 'Minimum 6 characters',
'new_password': 'New Password',
'new_password_hint': 'Enter new password',
'confirm_password': 'Confirm New Password',
'confirm_password_hint': 'Confirm password',
'confirm_password_required': 'Please confirm your password',
'passwords_no_match': 'Passwords do not match',
'update_password': 'Update Password',
'password_updated': 'Password updated successfully!',


"unknown": "Unknown",
"language_english": "English",
"language_arabic": "Arabic",
"visual_assistance_mode": "Visual Assistance Mode",
"premium": "Premium",
"verified": "Verified",
"safety_topic": "Safety",
"institutions_topic": "Institutions",
"app_guidelines_intro": "Find practical guidance for the chatbot, medical reminders, emergency assistance, accessibility tools, and support centers.",
"guidelines_support_description": "Send us your thoughts or report anything unclear through the feedback screen.",
"guideline_chatbot_title": "Using the AI Chatbot",
"guideline_chatbot_description": "Open Quick Access and choose Intelligent Assistant, or go to the Chat screen from the app. You can ask for help with navigation and accessibility support.",
"open_chatbot": "Open Chatbot",
"guideline_reminders_title": "Setting Medical Reminders",
"guideline_reminders_description": "Open Quick Access and choose Medical Reminders. Tap the plus (+) button to add a reminder, choose a time, and then manage each dose by marking it as taken or skipped.",
"open_reminders": "Open Reminders",
"guideline_accessibility_title": "Browsing Accessibility Resources",
"guideline_accessibility_description": "Open Quick Access and choose Accessibility Guidelines to view rights, tips, and helpful resources. You can also use the search bar and category filters inside Accessibility Hub.",
"open_accessibility_hub": "Open Accessibility Hub",
"guideline_emergency_title": "Using Emergency Assistance",
"guideline_emergency_description": "Open Quick Access and choose Emergency Call. From there you can manage emergency contacts, open the SOS flow, and long-press the SOS button to activate the emergency countdown.",
"open_emergency": "Open Emergency",
"guideline_institutions_title": "Finding Support Centers",
"guideline_institutions_description": "Use the search bar on Home or open the Institutions tab to browse active support centers. You can filter institutions by disability type and open details before booking a service.",
"open_institutions": "Open Institutions",
"guidelines_showing_all_one": "Showing {count} guideline",
"guidelines_showing_all_many": "Showing {count} guidelines",
"guidelines_showing_query_one": "Showing {count} result for \"{query}\"",
"guidelines_showing_query_many": "Showing {count} results for \"{query}\"",
"guidelines_showing_topic_one": "Showing {count} guideline in {topic}",
"guidelines_showing_topic_many": "Showing {count} guidelines in {topic}",
"guidelines_showing_both_one": "Showing {count} result for \"{query}\" in {topic}",
"guidelines_showing_both_many": "Showing {count} results for \"{query}\" in {topic}",
"no_guidelines_found": "No guidelines found",
"no_guidelines_found_desc": "Try another keyword or clear the selected topic to see all guidance topics.",

    "institution_portal_login_error": "This account belongs to the institution portal. Please use the institution app instead.",
"login_invalid_credentials_error": "This email is not registered or the password is incorrect. Please check your details or create a new account first.",
"network_error_try_again": "Unable to connect right now. Please check your internet connection and try again.",
"too_many_login_attempts": "Too many login attempts. Please wait a moment and try again.",
"login_failed_generic": "Login failed. Please try again.",
"signup_email_registered_error": "This email is already registered. Please log in instead.",
"signup_institution_email_error": "This email is already registered as an institution account. Please use the institution app instead.",
"signup_failed_generic": "Sign up failed. Please try again.",
    "friend": "Friend",
  "institution_about": "About",
  "institution_no_description": "No institution description available yet.",
  "institution_availability_notes": "Availability Notes",
  "minutes_short": "min",
  "status_cancelled": "Cancelled",
  "chat_welcome_message": "Hi! I'm Qudra AI. How can I help you today?",
  "resource_created_success": "Resource created successfully",
  "resource_updated_success": "Resource updated successfully",
  "resource_deleted_success": "Resource deleted successfully",

  "delete_reminder_confirm": "Delete \"{title}\"?",
  "mark_as_taken": "Mark as taken",
  "status_taken_today": "Taken today",
  "status_skipped_today": "Skipped today",
  "status_missed": "Missed",
  "failed_load_reminders": "Failed to load reminders",
  "valid_reminder_time": "Please choose a valid reminder time",
  "failed_add_reminder": "Failed to add reminder",
  "failed_delete_reminder": "Failed to delete reminder",
  "failed_update_reminder_status": "Failed to update status",
  "failed_mark_taken": "Failed to mark dose as taken",
  "failed_skip_dose": "Failed to skip dose",

  "emergency_title": "Emergency",
  "emergency_phase_placeholder": "Phase 2 passed successfully.\nConnect the main screen here in Phase 3.",
  "emergency_unexpected_error": "An unexpected error occurred.",
  "emergency_profile_setup_not_linked": "Profile setup screen is not connected yet.",
  "emergency_sos_not_linked": "SOS flow will be connected later.",
  "emergency_contacts_not_linked": "Contacts screen will be connected later.",
  "emergency_load_error": "An error occurred while loading emergency data.",
  "location_service_disabled_message": "Location service is disabled on the device. Turn on location first so the app can share your location in emergencies.",
  "location_service_open_settings_message": "Location service is disabled on the device. Open location settings and try again.",
  "location_permission_denied_message": "Location permission has not been granted yet. You can try again or skip for now.",
  "location_permission_error": "Unable to access location permission.",
  "emergency_direct_services": "Direct Emergency Services",
  "emergency_service_police": "Police",
  "emergency_service_ambulance": "Ambulance",
  "emergency_service_fire": "Fire Dept.",
  "emergency_quick_needs": "Quick Needs",
  "quick_need_cant_speak": "I can't speak",
  "quick_need_hard_of_hearing": "Hard of hearing",
  "quick_need_medical_case": "Medical case",
  "quick_need_need_caregiver": "I need a caregiver",
  "quick_need_in_danger": "I am in danger",
  "quick_need_need_help_now": "I need help now",
  "emergency_location_ready": "Location is ready to share",
  "emergency_location_not_ready": "Location is not ready right now",
  "emergency_location_ready_subtitle": "The app will be able to share your location during emergencies.",
  "emergency_location_not_ready_subtitle": "Check that location service is enabled and permission is granted from phone settings.",
  "emergency_sos_press_hold": "Press and hold to activate",
  "emergency_circle_title": "Emergency Circle",
  "emergency_circle_add": "Add",
  "emergency_circle_manage": "Manage",
  "emergency_circle_empty_title": "No emergency contacts yet",
  "emergency_circle_empty_subtitle": "Add trusted people such as a parent, caregiver, or doctor.",
  "emergency_circle_add_contacts": "Add Contacts",
  "emergency_contact_primary": "Primary",
  "app_name": "Qudra",
  "emergency_contacts_title": "Emergency Contacts",
  "emergency_contact_add": "Add Contact",
  "emergency_contact_add_single": "Add Emergency Contact",
  "emergency_contact_delete_title": "Delete Contact",
  "emergency_contact_delete_confirm": "Do you want to remove \"{name}\" from emergency contacts?",
  "emergency_contacts_empty_title": "No emergency contacts",
  "emergency_contacts_empty_subtitle": "Add trusted people such as a parent, caregiver, or doctor so they appear on the main screen and emergency card.",
  "emergency_contact_set_primary": "Set as Primary",
  "emergency_active_title": "Active Emergency",
  "emergency_active_subtitle": "You can now share your status or location and contact emergency services directly.",
  "emergency_current_location": "Current Location",
  "emergency_location_available_fallback": "Location is available",
  "emergency_location_unavailable": "Location is currently unavailable.",
  "emergency_send_urgent_alert": "Send urgent alert",
  "emergency_open_card": "Open Card",
  "emergency_card_not_linked": "Emergency card will be connected in Phase 7.",
  "emergency_direct_call": "Direct Call",
  "emergency_service_unified": "Emergency",
  "emergency_contacts_empty_inline": "No emergency contacts yet.",
  "emergency_im_safe": "I'm Safe",
  "emergency_card_title": "Emergency Card",
  "emergency_card_phase_placeholder": "Phase 6 passed successfully.\nThe full emergency card will be built in Phase 7.",
  "emergency_profile_setup_title": "Emergency Profile Setup",
  "emergency_profile_full_name_hint": "Enter your name as shown on your ID",
  "emergency_blood_type": "Blood Type",
  "emergency_select_blood_type": "Select blood type",
  "emergency_preferred_communication": "Preferred Communication Method",
  "emergency_communication_text": "Text",
  "emergency_communication_sign": "Sign Language",
  "emergency_communication_voice": "Voice",
  "emergency_important_medical_notes": "Important Medical Notes",
  "emergency_medical_notes_hint": "Any chronic conditions or important information needed during assistance...",
  "emergency_allergies_medications": "Allergies and Medications",
  "emergency_allergies_hint": "List any food or medication allergies and current medications...",
  "emergency_profile_local_save_notice": "This data is stored locally on this device only for emergency use.",
  "emergency_vibration_alert_title": "Enable vibration on alert",
  "emergency_vibration_alert_subtitle": "Strong tactile response during emergency situations",
  "emergency_saving": "Saving...",
  "emergency_profile_section_title": "Profile",
  "emergency_profile_no_data": "No profile data available.",
  "emergency_medical_info_title": "Medical Information",
  "emergency_no_medical_notes": "No medical notes recorded.",
  "emergency_no_allergies_medications": "No allergies or medications recorded.",
  "emergency_share_card": "Share Card",
  "emergency_sos_activation_title": "Activate SOS",
  "emergency_sos_activation_banner": "The emergency state will be activated automatically once the countdown ends.",
  "emergency_sos_activation_countdown": "Will activate in {seconds} seconds",
  "emergency_sos_activation_cancel_hint": "You can cancel now if this was triggered by mistake.",
  "permission_location_title": "Location permission\nis not enabled",
  "permission_location_subtitle": "We need access to your location so it can be shared with your contacts during emergencies.",
  "permission_location_enabling": "Enabling...",
  "permission_location_enable": "Enable location permission",
  "permission_open_location_settings": "Open location settings",
  "permission_skip_now": "Skip for now",
  "app_name": "Qudra",
  "emergency_contacts_title": "Emergency Contacts",
  "emergency_contact_add": "Add Contact",
  "emergency_contact_add_single": "Add Emergency Contact",
  "emergency_contact_delete_title": "Delete Contact",
  "emergency_contact_delete_confirm": "Do you want to remove \"{name}\" from emergency contacts?",
  "emergency_contacts_empty_title": "No emergency contacts",
  "emergency_contacts_empty_subtitle": "Add trusted people such as a parent, caregiver, or doctor so they appear on the main screen and emergency card.",
  "emergency_contact_set_primary": "Set as Primary",
  "emergency_contact_load_error": "Unable to load contacts.",
  "emergency_contact_add_error": "Unable to add contact.",
  "emergency_contact_update_error": "Unable to update contact.",
  "emergency_contact_delete_error": "Unable to delete contact.",
  "emergency_contact_primary_error": "Unable to update the primary contact.",
  "emergency_active_title": "Active Emergency",
  "emergency_active_subtitle": "You can now share your status or location and contact emergency services directly.",
  "emergency_current_location": "Current Location",
  "emergency_location_available_fallback": "Location is available",
  "emergency_location_unavailable": "Location is currently unavailable.",
  "emergency_send_urgent_alert": "Send urgent alert",
  "emergency_open_card": "Open Card",
  "emergency_card_not_linked": "Emergency card will be connected in Phase 7.",
  "emergency_direct_call": "Direct Call",
  "emergency_service_unified": "Emergency",
  "emergency_contacts_empty_inline": "No emergency contacts yet.",
  "emergency_im_safe": "I'm Safe",
  "emergency_active_load_error": "Unable to load active emergency data.",
  "emergency_card_title": "Emergency Card",
  "emergency_card_phase_placeholder": "Phase 6 passed successfully.\nThe full emergency card will be built in Phase 7.",
  "emergency_profile_setup_title": "Emergency Profile Setup",
  "emergency_profile_full_name_hint": "Enter your name as shown on your ID",
  "emergency_blood_type": "Blood Type",
  "emergency_select_blood_type": "Select blood type",
  "emergency_preferred_communication": "Preferred Communication Method",
  "emergency_communication_text": "Text",
  "emergency_communication_sign": "Sign Language",
  "emergency_communication_voice": "Voice",
  "emergency_communication_note_text": "Please communicate by text",
  "emergency_communication_note_sign": "I use sign language",
  "emergency_communication_note_voice": "I prefer voice communication",
  "emergency_communication_note_default": "Please communicate in a suitable way",
  "emergency_important_medical_notes": "Important Medical Notes",
  "emergency_medical_notes_hint": "Any chronic conditions or important information needed during assistance...",
  "emergency_allergies_medications": "Allergies and Medications",
  "emergency_allergies_hint": "List any food or medication allergies and current medications...",
  "emergency_profile_local_save_notice": "This data is stored locally on this device only for emergency use.",
  "emergency_vibration_alert_title": "Enable vibration on alert",
  "emergency_vibration_alert_subtitle": "Strong tactile response during emergency situations",
  "emergency_saving": "Saving...",
  "emergency_profile_section_title": "Profile",
  "emergency_profile_no_data": "No profile data available.",
  "emergency_medical_info_title": "Medical Information",
  "emergency_no_medical_notes": "No medical notes recorded.",
  "emergency_no_allergies_medications": "No allergies or medications recorded.",
  "emergency_share_card": "Share Card",
  "emergency_card_share_subject": "Qudra Emergency Profile Card",
  "emergency_profile_card_load_error": "Unable to load the emergency card.",
  "emergency_sos_activation_title": "Activate SOS",
  "emergency_sos_activation_banner": "The emergency state will be activated automatically once the countdown ends.",
  "emergency_sos_activation_countdown": "Will activate in {seconds} seconds",
  "emergency_sos_activation_cancel_hint": "You can cancel now if this was triggered by mistake.",
  "emergency_sos_activated_short": "Activated",
  "permission_location_title": "Location permission\nis not enabled",
  "permission_location_subtitle": "We need access to your location so it can be shared with your contacts during emergencies.",
  "permission_location_enabling": "Enabling...",
  "permission_location_enable": "Enable location permission",
  "permission_open_location_settings": "Open location settings",
  "permission_skip_now": "Skip for now",
  "emergency_disability_speech": "Speech",
  "emergency_disability_mental": "Mental",
  "emergency_validation_full_name": "Please enter your full name",
  "emergency_validation_disability_type": "Please choose the disability type",
  "emergency_validation_blood_type": "Please choose the blood type",
  "emergency_profile_save_error": "An error occurred while saving the data. Please try again.",
  "emergency_share_intro_active": "I am in an emergency.",
  "emergency_alert_share_subject": "Qudra Emergency Alert",

  "emergency_contact_form_add_title": "Add Emergency Contact",
  "emergency_contact_form_edit_title": "Edit Emergency Contact",
  "emergency_contact_name_label": "Name",
  "emergency_contact_relation_label": "Relation / Role",
  "emergency_contact_phone_label": "Phone Number",
  "emergency_contact_name_validation": "Please enter the name",
  "emergency_contact_relation_validation": "Please enter the relation",
  "emergency_contact_phone_validation": "Please enter the phone number",
  "emergency_contact_phone_invalid": "Invalid phone number",
  "emergency_contact_make_primary": "Make this the primary contact",
  "emergency_contact_make_primary_subtitle": "This contact will be marked as the first emergency contact.",
  "emergency_profile_intro_title": "Your life-saving\ninformation",
  "emergency_profile_intro_subtitle": "This information helps emergency teams or the right supporter reach you quickly when needed.",
  "institution_no_ratings": "No ratings yet",
"institution_rating_summary_compact": "{average} • {count} reviews",
"institution_rating_summary_one": "{average} • {count} review",
"institution_rating_summary_many": "{average} • {count} reviews",
"feedback_rating_range_error": "Rating must be between 1 and 5.",
"feedback_user_not_logged_in": "User is not logged in.",
  "service_working_hours": "Working Hours",
  "booking_choose_suitable_time": "Choose a Suitable Time",
  "booking_choose_day_first_for_times": "Please choose a day first to see the available times.",
  "booking_no_available_times_for_day": "No appointment times are available on this day.",
  "full_name_required": "Full name is required",
  "full_name_too_short": "Full name must be at least 3 characters",

  "phone_required": "Phone number is required",
  "phone_invalid": "Please enter a valid phone number",

  "responsible_person_required": "Responsible person is required",
  "responsible_person_invalid": "Please enter a valid responsible person name",

  "age_required": "Age is required",

  "gender_required": "Please select a gender",
  "disability_type_required": "Please select a disability type",

  // =========================
  // Care Plans
  // =========================
  "care_plans": "Care Plans",
  "care_plans_subtitle": "Track medication, feeding guidance, rehabilitation exercises, and learning goals in one place.",
  "add_care_plan_item": "Add Care Plan Item",
  "add_care_plan_item_subtitle": "Choose whether this item is for medication, feeding, rehabilitation, or learning goals.",

  // =========================
  // Care Plan Types
  // =========================
  "plan_type_all": "All",
  "plan_type_medication": "Medication",
  "plan_type_feeding": "Feeding",
  "plan_type_rehab": "Rehabilitation",
  "plan_type_learning": "Learning",

  // =========================
  // Care Plans Progress
  // =========================
  "tasks_completed": "Tasks completed",
  "no_tasks_scheduled": "No tasks scheduled",
  "all_tasks_completed": "All tasks completed",
  "no_upcoming_tasks": "No upcoming tasks",
  "daily_care_plan_items": "Daily Care Plan Items",
  "no_care_plan_items": "No care plan items yet. Tap + to add medication, feeding, rehab, or learning goals.",
  "no_items_in_selected_plan": "No items in this selected care plan category yet.",

  // =========================
  // Feeding Guidance
  // =========================
  "feeding_title_label": "Meal / Feeding Reminder",
  "feeding_guidance": "Feeding Guidance",
  "enter_feeding_title": "Please enter the meal or feeding reminder title",
  "enter_feeding_guidance": "Please enter feeding guidance or notes",
  "general_feeding_disclaimer": "Feeding guidance is general support and does not replace medical or nutrition advice.",

  // =========================
  // Rehabilitation Plans
  // =========================
  "rehab_title_label": "Rehabilitation Exercise",
  "rehab_notes": "Exercise Notes",
  "enter_rehab_title": "Please enter the rehabilitation exercise title",
  "enter_rehab_notes": "Please enter rehabilitation notes",
  "general_rehab_disclaimer": "Rehabilitation guidance is general support. Follow your therapist or doctor's instructions when available.",

  // =========================
  // Learning Goals
  // =========================
  "learning_title_label": "Learning Goal",
  "learning_goal_details": "Goal Details",
  "enter_learning_title": "Please enter the learning goal title",
  "enter_learning_goal_details": "Please enter learning goal details",

  // =========================
  // Care Plans General Notice
  // =========================
  "care_plans_general_disclaimer": "Care Plans provide general daily support for medication, feeding, rehabilitation, and learning goals. They do not replace professional medical advice.",
  "delete_care_plan_item": "Delete Care Plan Item?",

  // =========================
  // Accessibility Awareness Hub
  // =========================
  "accessibility_awareness_hub": "Accessibility Awareness Hub",
  "awareness_hub_title": "Accessibility Awareness Hub",
  "awareness_hub_subtitle": "Explore rights, practical tips, articles, and videos designed to improve daily quality of life.",
  "awareness_results_count": "{count} resources found",

  // =========================
  // Awareness Content Types
  // =========================
  "content_type_all": "All",
  "content_type_tip": "Tip",
  "content_type_tips": "Tips",
  "content_type_right": "Right",
  "content_type_rights": "Rights",
  "content_type_article": "Article",
  "content_type_articles": "Articles",
  "content_type_video": "Video",
  "content_type_videos": "Videos",

  // =========================
  // Daily Tips & Featured Resources
  // =========================
  "daily_tip": "Daily Tip",
  "featured": "Featured",
  "read_time": "Read time",

  // =========================
  // External Resource Actions
  // =========================
  "watch_video": "Watch Video",
  "open_article": "Open Article",
  "resource_url_missing": "No link is available for this resource.",
  "resource_url_invalid": "This resource link is not valid.",
  "resource_url_open_error": "Unable to open this resource right now.",

  // =========================
  // Empty States
  // =========================
  "no_awareness_resources_found": "No resources found",
  "no_awareness_resources_found_desc": "Try changing the search text, content type, or disability filter.",

  // =========================
  // Smart Accessible Map
  // =========================
  "smart_accessible_map": "Smart Accessible Map",
  "smart_accessible_map_placeholder": "Nearby restaurants, healthcare, pharmacies, and transport places will appear here with accessibility priority.",
  "smart_map_filter_all": "All",
  "smart_map_filter_food": "Food",
  "smart_map_filter_healthcare": "Healthcare",
  "smart_map_filter_pharmacy": "Pharmacy",
  "smart_map_filter_transport": "Transport",
  "smart_map_accessible": "Accessible",
  "smart_map_limited_access": "Limited access",
  "smart_map_not_accessible": "Not accessible",
  "smart_map_unknown_accessibility": "Unknown accessibility",
  "smart_map_accessible_only": "Accessible only",
  "smart_map_loading_places": "Loading nearby accessible places...",
  "smart_map_failed_load_places": "Could not load nearby places right now.",
  "smart_map_location_unavailable": "Location is unavailable right now.",
  "smart_map_location_permission_denied": "Location permission is required to show nearby places.",
  "smart_map_location_permission_denied_forever": "Location permission is permanently denied. Please enable it from settings.",
  "smart_map_location_service_disabled": "Location service is disabled. Please turn it on to see nearby places.",
  "smart_map_directions_error": "Could not open directions right now.",
  "smart_map_open_directions": "Open directions",
  "smart_map_nearby_results": "{count} nearby places",
  "smart_map_no_places_found": "No places found",
  "smart_map_no_places_found_desc": "Try changing the filter or refreshing your location.",
  "smart_map_address": "Address",
  "smart_map_phone": "Phone",
  "smart_map_accessibility_notes": "Accessibility notes",
  "smart_map_data_notice": "Accessibility information depends on public OpenStreetMap contributions and may be incomplete. Please confirm with the place before visiting.",
  "km_short": "km",
  // =========================
  // Updated App Guidelines
  // =========================
  "care_plans_topic": "Care Plans",
  "smart_map_topic": "Smart Map",
  "awareness_topic": "Awareness",

  "guideline_care_plans_title": "Manage your daily Care Plans",
  "guideline_care_plans_description": "Use Care Plans to organize medication reminders, feeding guidance, rehabilitation exercises, and learning goals in one place.",
  "open_care_plans": "Open Care Plans",

  "guideline_smart_map_title": "Find nearby accessible places",
  "guideline_smart_map_description": "Use the Smart Accessible Map to discover nearby restaurants, healthcare places, pharmacies, and transport stops with accessibility priority.",
  "open_smart_map": "Open Smart Map",

  "guideline_awareness_hub_title": "Explore accessibility awareness content",
  "guideline_awareness_hub_description": "Read practical tips, rights, articles, daily tips, and watch videos designed to support accessibility and daily independence.",
};